import {z} from 'zod';
import {signedCents,decimal} from './financeReports';
import {csvCell,isReportDate} from './trialBalance';
const id=z.string().uuid(),money=z.string().refine(v=>{try{signedCents(v);return true;}catch{return false;}},'Invalid exact amount'),date=z.string().refine(isReportDate),revision=z.string().regex(/^[a-f0-9]{32}$/);
export const sectionRules={CASH:['asset','closing',1],RESTRICTED_CASH_CURRENT:['asset','closing',1],RESTRICTED_CASH_NONCURRENT:['asset','closing',1],TRADE_RECEIVABLES:['asset','closing',1],OTHER_CURRENT_ASSETS:['asset','closing',1],NONCURRENT_ASSETS:['asset','closing',1],CURRENT_LIABILITIES:['liability','closing',-1],NONCURRENT_LIABILITIES:['liability','closing',-1],CAPITAL:['equity','closing',-1],RETAINED_EARNINGS:['equity','closing',-1],OTHER_EQUITY:['equity','closing',-1],REVENUE:['revenue','income',-1],COST_OF_REVENUE:['expense','income',1],OPERATING_EXPENSES:['expense','income',1],OTHER_INCOME:['revenue','income',-1],OTHER_EXPENSES:['expense','income',1],INCOME_TAX:['expense','income',1]} as const;
export const categorySections={CUSTOMER_RECEIPTS:'OPERATING',SUPPLIER_EMPLOYEE_PAYMENTS:'OPERATING',OTHER_OPERATING:'OPERATING',INTEREST:'OPERATING',INCOME_TAXES:'OPERATING',CAPITAL_EXPENDITURES:'INVESTING',ASSET_DISPOSALS:'INVESTING',INVESTMENTS_LOANS:'INVESTING',OTHER_INVESTING:'INVESTING',BORROWINGS:'FINANCING',EQUITY:'FINANCING',DIVIDENDS:'FINANCING',OTHER_FINANCING:'FINANCING',TRANSFER:'TRANSFER'} as const;
const allocation=z.object({category:z.string(),amount:money});
const source=z.object({lineId:id,journalId:id,number:z.string(),date,accountId:id,code:z.string(),name:z.string(),amount:money,classificationId:id.nullable(),version:z.number().int().nonnegative(),allocations:z.array(allocation)});
const category=z.object({category:z.string(),label:z.string(),section:z.string(),receipts:money,payments:money,net:money});
const row=z.object({accountId:id,code:z.string(),name:z.string(),accountType:z.enum(['asset','liability','equity','revenue','expense']),closing:money,income:money});
export const mappedStatementsSchema=z.object({policyId:id,policyVersion:z.number().int().positive(),sections:z.array(z.object({section:z.string(),label:z.string(),accountType:z.string(),basis:z.enum(['closing','income']),sign:z.number().int(),total:money,rows:z.array(row.extend({amount:money}))})),unmapped:z.array(row),assets:money,liabilities:money,recordedEquity:money,unclosedEarnings:money,totalEquity:money,liabilitiesAndEquity:money,grossProfit:money,operatingProfit:money,netIncome:money,complete:z.boolean()});
export type MappedStatements=z.infer<typeof mappedStatementsSchema>;
export const cashFlowSchema=z.object({entityId:id,currency:z.string().regex(/^[A-Z]{3}$/),from:date,through:date,policyId:id,policyVersion:z.number().int().positive(),cashAccounts:z.array(id),cashCoverageComplete:z.boolean(),ledgerRevision:revision,openingCash:money,closingCash:money,classifiedMovement:money,unclassifiedMovement:money,unclassifiedCount:z.number().int().nonnegative(),transferNet:money,categories:z.array(category),sources:z.array(source),complete:z.boolean(),revision,generatedAt:z.string().optional()});
export type CashFlow=z.infer<typeof cashFlowSchema>;
export const groupCashFlowSchema=z.object({groupId:id,currency:z.string().regex(/^[A-Z]{3}$/),from:date,through:date,openingCash:money,closingCash:money,translatedMovement:money,classifiedMovement:money,unclassifiedMovement:money,unclassifiedCount:z.number().int().nonnegative(),roundingDifference:money,exchangeEffect:money,categories:z.array(category),sources:z.array(source.extend({entityId:id,currency:z.string(),rate:z.string(),translatedAmount:money,eliminated:z.boolean()})),members:z.array(z.object({entityId:id,policyId:id,policyVersion:z.number().int().positive(),revision,complete:z.boolean(),openingCash:money,closingCash:money})),complete:z.boolean(),revision});
export type GroupCashFlow=z.infer<typeof groupCashFlowSchema>;
export const statementCashTotal=(s:MappedStatements)=>decimal(s.sections.filter(k=>['CASH','RESTRICTED_CASH_CURRENT','RESTRICTED_CASH_NONCURRENT'].includes(k.section)).reduce((v,k)=>v+signedCents(k.total),0n));
const unique=(values:string[])=>new Set(values).size===values.length;
function checkSource(s:z.infer<typeof source>,from:string,through:string){
 const n=signedCents(s.amount);if(!n||s.date<from||s.date>through||!unique(s.allocations.map(a=>a.category)))throw new Error('Invalid cash source scope or allocations.');
 if(s.classificationId===null){if(s.version!==0||s.allocations.length)throw new Error('Unclassified cash source carries conflicting approval data.');}
 else if(s.version<1||s.allocations.length===0||s.allocations.some(a=>!(a.category in categorySections)||signedCents(a.amount)<=0n)||s.allocations.reduce((v,a)=>v+signedCents(a.amount),0n)!==(n<0n?-n:n))throw new Error('Cash classifications do not equal the complete ledger line.');
}
function checkCategories(categories:z.infer<typeof category>[],expected:Map<string,{receipts:bigint;payments:bigint}>){
 if(categories.length!==Object.keys(categorySections).length||!unique(categories.map(c=>c.category)))throw new Error('Cash category coverage is incomplete.');
 for(const c of categories){const v=expected.get(c.category)??{receipts:0n,payments:0n};if(categorySections[c.category as keyof typeof categorySections]!==c.section||signedCents(c.receipts)!==v.receipts||signedCents(c.payments)!==v.payments||signedCents(c.net)!==v.receipts-v.payments)throw new Error('Cash category totals do not reconcile to their sources.');}
}
export function parseMappedStatements(value:unknown):MappedStatements{
 const r=mappedStatementsSchema.parse(value),seen=new Set<string>(),totals=new Map<string,bigint>();let assets=0n,liabilities=0n,equity=0n,unclosed=0n,income=0n;
 function account(a:z.infer<typeof row>){if(seen.has(a.accountId))throw new Error('Duplicate statement account.');seen.add(a.accountId);const c=signedCents(a.closing),i=signedCents(a.income);if(a.accountType==='asset')assets+=c;else if(a.accountType==='liability')liabilities-=c;else if(a.accountType==='equity')equity-=c;else unclosed-=c;if(!['revenue','expense'].includes(a.accountType)&&i!==0n)throw new Error('Statement income contains a balance-sheet account.');income-=i;}
 if(r.sections.length!==Object.keys(sectionRules).length||!unique(r.sections.map(s=>s.section)))throw new Error('Statement section coverage is incomplete.');
 for(const s of r.sections){const rule=sectionRules[s.section as keyof typeof sectionRules];if(!rule||s.accountType!==rule[0]||s.basis!==rule[1]||s.sign!==rule[2])throw new Error('Invalid statement presentation section.');let total=0n;for(const a of s.rows){account(a);const value=signedCents(a[s.basis])*BigInt(s.sign);if(a.accountType!==s.accountType||value!==signedCents(a.amount))throw new Error('Statement account does not match its presentation.');total+=value;}if(total!==signedCents(s.total))throw new Error('Statement section total does not reconcile.');totals.set(s.section,total);}
 for(const a of r.unmapped)account(a);const gross=totals.get('REVENUE')!-totals.get('COST_OF_REVENUE')!;
 if(assets!==liabilities+equity+unclosed||assets!==signedCents(r.assets)||liabilities!==signedCents(r.liabilities)||equity!==signedCents(r.recordedEquity)||unclosed!==signedCents(r.unclosedEarnings)||equity+unclosed!==signedCents(r.totalEquity)||assets!==signedCents(r.liabilitiesAndEquity)||income!==signedCents(r.netIncome)||gross!==signedCents(r.grossProfit)||gross-totals.get('OPERATING_EXPENSES')!==signedCents(r.operatingProfit)||r.complete!==(r.unmapped.length===0))throw new Error('Financial statements do not reconcile.');return r;
}
export function parseCashFlow(value:unknown):CashFlow{
 const r=cashFlowSchema.parse(value);if(r.from>r.through||!unique(r.cashAccounts)||!unique(r.sources.map(s=>s.lineId)))throw new Error('Cash-flow scope is invalid.');let movement=0n,unknown=0n,count=0;const expected=new Map<string,{receipts:bigint;payments:bigint}>();
 for(const s of r.sources){checkSource(s,r.from,r.through);if(!r.cashAccounts.includes(s.accountId))throw new Error('Cash source is outside the declared accounts.');const n=signedCents(s.amount);movement+=n;if(s.classificationId===null){unknown+=n;count++;}for(const a of s.allocations){const v=expected.get(a.category)??{receipts:0n,payments:0n};if(n>0n)v.receipts+=signedCents(a.amount);else v.payments+=signedCents(a.amount);expected.set(a.category,v);}}
 checkCategories(r.categories,expected);const classified=r.categories.reduce((v,c)=>v+signedCents(c.net),0n),transfer=signedCents(r.categories.find(c=>c.category==='TRANSFER')!.net);
 if(unknown!==signedCents(r.unclassifiedMovement)||count!==r.unclassifiedCount||classified!==signedCents(r.classifiedMovement)||classified+unknown!==movement||signedCents(r.openingCash)+movement!==signedCents(r.closingCash)||transfer!==signedCents(r.transferNet)||r.complete!==(r.cashCoverageComplete&&count===0&&transfer===0n))throw new Error('Cash flow does not reconcile to the bank ledger.');return r;
}
function translated(cents:bigint,rate:string){if(!/^(0|[1-9]\d{0,5})(\.\d{1,8})?$/.test(rate))throw new Error('Invalid cash translation rate.');const [whole,fraction='']=rate.split('.'),factor=BigInt(whole+fraction),scale=10n**BigInt(fraction.length),absolute=cents<0n?-cents:cents;if(factor<=0n)throw new Error('Invalid cash translation rate.');return ((absolute*factor*2n+scale)/(2n*scale))*(cents<0n?-1n:1n);}
export function parseGroupCashFlow(value:unknown):GroupCashFlow{
 const r=groupCashFlowSchema.parse(value);if(r.from>r.through||!unique(r.members.map(m=>m.entityId))||!unique(r.sources.map(s=>s.lineId)))throw new Error('Group cash scope is invalid.');const aggregates=new Map<string,{category:string;rate:string;receipts:bigint;payments:bigint}>(),expected=new Map<string,{receipts:bigint;payments:bigint}>();let movement=0n,unknown=0n,count=0,eliminated=0n;
 for(const s of r.sources){checkSource(s,r.from,r.through);if(!r.members.some(m=>m.entityId===s.entityId)||translated(signedCents(s.amount),s.rate)!==signedCents(s.translatedAmount))throw new Error('Group cash translation does not match its source.');const n=signedCents(s.translatedAmount);movement+=n;if(s.eliminated){eliminated+=n;continue;}if(s.classificationId===null){unknown+=n;count++;}for(const a of s.allocations){const k=[s.entityId,s.date.slice(0,7),a.category].join(':'),v=aggregates.get(k)??{category:a.category,rate:s.rate,receipts:0n,payments:0n};if(v.rate!==s.rate)throw new Error('Conflicting monthly cash rates.');if(signedCents(s.amount)>0n)v.receipts+=signedCents(a.amount);else v.payments+=signedCents(a.amount);aggregates.set(k,v);}}
 for(const v of aggregates.values()){const e=expected.get(v.category)??{receipts:0n,payments:0n};e.receipts+=translated(v.receipts,v.rate);e.payments+=translated(v.payments,v.rate);expected.set(v.category,e);}checkCategories(r.categories,expected);
 const classified=r.categories.reduce((v,c)=>v+signedCents(c.net),0n),opening=r.members.reduce((v,m)=>v+signedCents(m.openingCash),0n),closing=r.members.reduce((v,m)=>v+signedCents(m.closingCash),0n);
 if(eliminated!==0n||count!==r.unclassifiedCount||unknown!==signedCents(r.unclassifiedMovement)||movement!==signedCents(r.translatedMovement)||classified!==signedCents(r.classifiedMovement)||movement-classified-unknown!==signedCents(r.roundingDifference)||opening!==signedCents(r.openingCash)||closing!==signedCents(r.closingCash)||opening+movement+signedCents(r.exchangeEffect)!==closing||r.complete!==(count===0&&r.members.every(m=>m.complete)))throw new Error('Group cash flow does not reconcile.');return r;
}
export const financialStatementsSchema=z.object({entityId:id,entityName:z.string(),currency:z.string(),from:date,through:date,ledgerRevision:revision,statements:z.unknown(),cashFlow:z.unknown(),cashBalanceAgrees:z.boolean(),complete:z.boolean(),revision,generatedAt:z.string()});
export function parseFinancialStatements(value:unknown,scope:{entity:string;from:string;through:string}){
 const r=financialStatementsSchema.parse(value),statements=parseMappedStatements(r.statements),cashFlow=parseCashFlow(r.cashFlow);if(r.entityId!==scope.entity||r.from!==scope.from||r.through!==scope.through||cashFlow.entityId!==r.entityId||cashFlow.from!==r.from||cashFlow.through!==r.through||cashFlow.currency!==r.currency||cashFlow.ledgerRevision!==r.ledgerRevision||cashFlow.policyId!==statements.policyId||cashFlow.policyVersion!==statements.policyVersion)throw new Error('Financial reporting scope changed.');const agrees=statementCashTotal(statements)===cashFlow.closingCash;if(r.cashBalanceAgrees!==agrees||r.complete!==(statements.complete&&cashFlow.complete&&agrees))throw new Error('Statement cash controls disagree.');return {...r,statements,cashFlow};
}
export type FinancialStatements=ReturnType<typeof parseFinancialStatements>;
export function financialStatementCsv(r:{currency:string;from:string;through:string;revision:string;statements:MappedStatements;cashFlow:CashFlow|GroupCashFlow},label:string){
 parseMappedStatements(r.statements);if('entityId' in r.cashFlow)parseCashFlow(r.cashFlow);else parseGroupCashFlow(r.cashFlow);
 const rows=[['Financial statements',label,'Currency',r.currency,'From',r.from,'Through',r.through],['Revision',r.revision,'Policy version',String(r.statements.policyVersion)],['Section','Account code','Account','Amount']];for(const s of r.statements.sections){for(const a of s.rows)rows.push([s.label,a.code,a.name,a.amount]);rows.push([s.label,'','TOTAL',s.total]);}for(const a of r.statements.unmapped)rows.push(['UNMAPPED',a.code,a.name,a.closing]);
 for(const [label,amount] of [['Gross profit',r.statements.grossProfit],['Operating profit',r.statements.operatingProfit],['Net income',r.statements.netIncome],['Unclosed earnings through end date',r.statements.unclosedEarnings],['Total equity',r.statements.totalEquity],['Opening cash',r.cashFlow.openingCash]])rows.push([label,'','',amount]);
 for(const c of r.cashFlow.categories)rows.push([c.section,'',c.label,c.net]);rows.push(['Unclassified cash','','',r.cashFlow.unclassifiedMovement]);if('exchangeEffect' in r.cashFlow)rows.push(['Exchange effect','','',r.cashFlow.exchangeEffect],['Translation rounding','','',r.cashFlow.roundingDifference]);rows.push(['Closing cash','','',r.cashFlow.closingCash]);
 return rows.map((r,i)=>r.map((v,j)=>i>2&&j===3?'"'+decimal(signedCents(v))+'"':csvCell(v)).join(',')).join('\r\n')+'\r\n';
}
export const statementContextSchema=z.object({entityId:id,groupId:id.nullable(),policy:z.object({id,version:z.number().int(),mappings:z.array(z.object({account_id:id,section:z.string()})),cash_accounts:z.array(id)}).nullable(),cashAccounts:z.array(id),accounts:z.array(z.object({id,code:z.string(),name:z.string(),type:z.string(),active:z.boolean()})),sections:z.array(z.object({section:z.string(),label:z.string(),account_type:z.string()})),categories:z.array(z.object({category:z.string(),label:z.string(),section:z.string()}))});
