import {z} from 'zod';
import {signedCents} from './financeReports';
const id=z.string().uuid(),money=z.string().regex(/^-?\d+\.\d{2}$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),rate=z.string().regex(/^\d+\.\d{8}$/);
const state=z.object({foreignRemaining:money,carrying:money,historicalRemaining:money,valuationDate:date,rate,voided:z.boolean()});
const schema=z.object({entityId:id,currency:z.string(),asOf:date,revision:z.string(),receivables:money,payables:money,pendingRemeasurement:z.number().int().nonnegative(),reconciled:z.boolean(),policy:z.object({id,receivable_account:id,payable_account:id,unrealized_gain:id,unrealized_loss:id,realized_gain:id,realized_loss:id}).nullable(),controls:z.array(z.object({accountId:id,code:z.string(),name:z.string(),expected:money,ledger:money,variance:money})),documents:z.array(z.object({id,kind:z.enum(['RECEIVABLE','PAYABLE']),number:z.string(),partyId:id,party:z.string(),date,dueDate:date,currency:z.string(),foreignNet:money,foreignTax:money,foreignTotal:money,functionalTotal:money,initialRate:rate,state,overdueDays:z.number().int().nonnegative(),agingBucket:z.enum(['CURRENT','1_30','31_60','61_90','OVER_90']),needsRemeasurement:z.boolean(),journalId:id,requestId:id,latestActiveEvent:id.nullable(),events:z.array(z.object({id,version:z.number().int().positive(),kind:z.enum(['REMEASURE','SETTLE','VOID','REVERSE']),date,rate:rate.nullable(),foreignAmount:money,functionalCash:money,before:state,after:state,journalId:id.nullable(),requestId:id,reverses:id.nullable()}))}))});
export type ForeignCurrencyReport=z.infer<typeof schema>;
export function convertedCents(amount:string,rate:string){const numerator=signedCents(amount)*BigInt(rate.replace('.',''));return (numerator+50000000n)/100000000n;}
export function parseForeignCurrencyReport(value:unknown){const r=schema.parse(value);let ar=0n,ap=0n,pending=0;const seen=new Set<string>();const check=(ok:unknown)=>{if(!ok)throw new Error('Foreign currency source balances do not reconcile.');};
 for(const d of r.documents){check(!seen.has(d.id)&&d.date<=r.asOf&&d.currency!==r.currency);seen.add(d.id);check(signedCents(d.foreignNet)+signedCents(d.foreignTax)===signedCents(d.foreignTotal)&&convertedCents(d.foreignTotal,d.initialRate)===signedCents(d.functionalTotal));check(signedCents(d.state.foreignRemaining)>=0n&&signedCents(d.state.foreignRemaining)<=signedCents(d.foreignTotal)&&signedCents(d.state.carrying)>=0n&&signedCents(d.state.historicalRemaining)>=0n);if(d.state.foreignRemaining==='0.00')check(d.state.carrying==='0.00'&&d.state.historicalRemaining==='0.00');check(!d.state.voided||d.state.foreignRemaining==='0.00');
  const needs=d.state.foreignRemaining!=='0.00'&&d.state.valuationDate<r.asOf;check(d.needsRemeasurement===needs);if(needs)pending++;if(d.kind==='RECEIVABLE')ar+=signedCents(d.state.carrying);else ap+=signedCents(d.state.carrying);
  let previous:z.infer<typeof state>={foreignRemaining:d.foreignTotal,carrying:d.functionalTotal,historicalRemaining:d.functionalTotal,valuationDate:d.date,rate:d.initialRate,voided:false};let dated=previous;let lastDate=d.date;const events=new Set<string>();for(const [i,e] of d.events.entries()){check(!events.has(e.id)&&e.version===i+1&&e.date>=lastDate&&JSON.stringify(e.before)===JSON.stringify(previous));check(e.kind==='REVERSE'?e.reverses&&events.has(e.reverses):e.reverses===null);events.add(e.id);previous=e.after;lastDate=e.date;if(e.date<=r.asOf)dated=e.after;}check(JSON.stringify(dated)===JSON.stringify(d.state));
 }
 check(ar===signedCents(r.receivables)&&ap===signedCents(r.payables)&&pending===r.pendingRemeasurement);for(const c of r.controls)check(signedCents(c.ledger)-signedCents(c.expected)===signedCents(c.variance));check(r.reconciled===r.controls.every(c=>c.variance==='0.00'));return r;
}
