import {Button} from '@/components/ui/button';
import {downloadFinanceEvidence} from '@/lib/groupFinance';
import {financialStatementCsv,type MappedStatements,type CashFlow,type GroupCashFlow} from '@/lib/financialStatements';
import {signedCents,decimal} from '@/lib/financeReports';
export function FinancialStatementView({statements:s,cashFlow:c,currency,from,through,revision,label,complete}:{statements:MappedStatements;cashFlow:CashFlow|GroupCashFlow;currency:string;from:string;through:string;revision:string;label:string;complete:boolean}){
 return <section className="space-y-4"><h2 className="text-lg font-semibold">Mapped financial statements · {label}</h2><p>Policy version {s.policyVersion} · {currency} · {from} — {through}</p><p role={complete?'status':'alert'}>{complete?'Statement and cash flow controls reconcile.':'Draft report: resolve unmapped accounts and cash flow controls before relying on these statements.'}</p>
  <div className="grid gap-2 sm:grid-cols-3"><p>Gross profit {s.grossProfit}</p><p>Operating profit {s.operatingProfit}</p><p>Net income {s.netIncome}</p><p>Assets {s.assets}</p><p>Liabilities {s.liabilities}</p><p>Total equity {s.totalEquity}</p></div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left">Balance sheet and income statement · approved account presentation</caption><thead><tr><th className="p-2 text-left">Section</th><th className="p-2 text-right">Amount</th></tr></thead><tbody>{s.sections.map(section=><tr key={section.section} className="border-t"><td className="p-2"><details><summary>{section.label}</summary>{section.rows.map(a=><p className="py-1" key={a.accountId}>{a.code} {a.name} · {a.amount}</p>)}</details></td><td className="p-2 text-right tabular-nums">{section.total}</td></tr>)}</tbody></table></div>
  <p>Unclosed earnings through end date: {s.unclosedEarnings}. Recorded retained earnings appear separately; fiscal closing transfers are excluded from period income.</p>
  {s.unmapped.length?<div role="alert"><h3 className="font-semibold">Accounts requiring presentation mapping</h3>{s.unmapped.map(a=><p key={a.accountId}>{a.code} {a.name}</p>)}</div>:null}
  <h3 className="font-semibold">Cash flow · direct method</h3><p>Opening cash {c.openingCash}</p>{['OPERATING','INVESTING','FINANCING','TRANSFER'].map(section=><details key={section} open={section!=='TRANSFER'}><summary>{section.charAt(0)+section.slice(1).toLowerCase()} · {decimal(c.categories.filter(k=>k.section===section).reduce((v,k)=>v+signedCents(k.net),0n))}</summary><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Cash category</th><th className="p-2 text-right">Receipts</th><th className="p-2 text-right">Payments</th><th className="p-2 text-right">Net cash</th></tr></thead><tbody>{c.categories.filter(k=>k.section===section).map(k=><tr key={k.category} className="border-t"><th className="p-2 text-left">{k.label}</th>{[k.receipts,k.payments,k.net].map((n,i)=><td className="p-2 text-right tabular-nums" key={i}>{n}</td>)}</tr>)}</tbody></table></div></details>)}
  <p>Unclassified cash: {c.unclassifiedMovement} across {c.unclassifiedCount} lines.</p>{'exchangeEffect' in c?<><p>Exchange-rate effect: {c.exchangeEffect} · Translation rounding: {c.roundingDifference}</p>{c.members.some(m=>!m.complete)?<p role="alert">One or more member cash reports still require complete classifications or bank-account coverage.</p>:null}</>:!c.cashCoverageComplete?<p role="alert">Registered cash accounts changed. Update the approved statement policy.</p>:null}<p className="font-semibold">Closing cash {c.closingCash}</p>
  <p className="text-sm">Cash flow totals include registered cash, cash equivalents and current or noncurrent restricted cash. Cash categories use independently approved source allocations. Internal cash transfers are excluded from operating, investing and financing totals. Noncash investing and financing transactions require accompanying disclosures.</p>
  <div className="flex gap-2"><Button variant="outline" onClick={()=>downloadFinanceEvidence(`financial-statements-${through}.csv`,financialStatementCsv({currency,from,through,revision,statements:s,cashFlow:c},`${complete?'Complete':'Draft'} · ${label}`),'text/csv;charset=utf-8')}>Export mapped statements CSV</Button><Button variant="outline" onClick={()=>downloadFinanceEvidence(`financial-statements-${through}.json`,JSON.stringify({label,complete,currency,from,through,revision,statements:s,cashFlow:c},null,2))}>Export statement evidence</Button></div>
 </section>;
}
