import type {ContractFinance} from '@/lib/contractFinance';
import {FinanceActionForm} from './FinanceActionForm';
import {TaxAssessmentFields} from './TaxAssessmentFields';
import {readTaxAssessment} from '@/lib/taxAccounting';
import {requestFinance} from '@/hooks/useFinanceApprovals';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

type Cycle=ContractFinance['cycles'][number];
export function RevenueRevisions({entity,cycle:c,canWrite}:{entity:string;cycle:Cycle;canWrite:boolean}){
 const latest=c.revisions.at(-1);
 return <section aria-label={`Revenue revisions for cycle ${c.number}`} className="space-y-4 rounded border p-4"><h3 className="font-semibold">Revenue revisions</h3><p>Record the approved transaction price and performance assessment. Prospective changes preserve revenue already recognized; catch-up changes adjust it on the revision date. Allocate the complete price across the original obligations. Invoice credits reduce overbilled consideration; supplemental invoices bill approved increases.</p>
  {c.revisions.map(r=><article key={r.id} className="space-y-2 border-t pt-3"><h4>Revision {r.version} · {r.date} · Transaction price {r.price} · Catch-up {r.amount}</h4><Table><TableHeader><TableRow><TableHead>Obligation</TableHead><TableHead>Treatment</TableHead><TableHead>Method</TableHead><TableHead>Allocation</TableHead><TableHead>Progress</TableHead></TableRow></TableHeader><TableBody>{r.plan.map(a=><TableRow key={a.key}><TableCell>{a.key}</TableCell><TableCell>{a.treatment}</TableCell><TableCell>{a.method}</TableCell><TableCell>{a.amount}</TableCell><TableCell>{a.method==='DAILY'?'By service date':a.progress+'%'}</TableCell></TableRow>)}</TableBody></Table><p>Approval: {r.requestId} · Journal: {r.journalId??'No net ledger change'}</p><details><summary>Performance evidence</summary>{r.plan.map(a=><p key={a.key}>{a.key}: {a.evidence}</p>)}</details></article>)}
  {canWrite?<details><summary>Prepare a revenue revision</summary><FinanceActionForm key={latest?.id??c.id} title="Request revenue revision" fields={[{name:'date',label:'Revision accounting date',type:'date'},{name:'price',label:'Revised net transaction price',value:c.price},{name:'reference',label:'Contract modification reference'},{name:'policy',label:'Distinctness, allocation and treatment assessment',type:'textarea'},{name:'variable',label:'Variable consideration and constraint assessment',type:'textarea'},{name:'reason',label:'Revision approval evidence'}]} submit={(v,key)=>requestFinance(entity,'CONTRACT_REVISE',{cycle_id:c.id,date:v.date,price:v.price,reference:v.reference,policy_evidence:v.policy,variable_consideration:v.variable,obligations:c.allocations.map((a,i)=>({key:a.key,amount:v['amount-'+i],treatment:v['treatment-'+i],method:v['method-'+i],starts_on:v['start-'+i],ends_on:v['end-'+i],progress:v['progress-'+i],evidence:v['evidence-'+i]}))},v.reason,key)}>
   {c.allocations.map((a,i)=>{const prior=latest?.plan.find(p=>p.key===a.key);return <fieldset key={a.key} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><legend>{a.description} ({a.key})</legend><label>Revised allocation for {a.key}<input aria-label={`Revised allocation for ${a.key}`} required name={'amount-'+i} defaultValue={prior?.amount??a.amount} className="block w-full rounded border bg-background p-2"/></label><label>Treatment for {a.key}<select name={'treatment-'+i} defaultValue="CATCH_UP" className="block w-full rounded border bg-background p-2"><option value="CATCH_UP">Cumulative catch-up</option><option value="PROSPECTIVE">Prospective remaining service</option></select></label><label>Recognition method for {a.key}<select name={'method-'+i} defaultValue={prior?.method??a.method} className="block w-full rounded border bg-background p-2"><option value="DAILY">Daily service</option><option value="PERCENT_COMPLETE">Reviewed percentage complete</option><option value="MILESTONE">Milestone transfer</option></select></label><label>Progress percentage for {a.key}<input required name={'progress-'+i} defaultValue={prior?.progress??'0'} className="block w-full rounded border bg-background p-2"/></label><label>Revised service starts for {a.key}<input required name={'start-'+i} type="date" defaultValue={prior?.starts_on??c.startsOn} className="block w-full rounded border bg-background p-2"/></label><label>Revised service ends for {a.key}<input required name={'end-'+i} type="date" defaultValue={prior?.ends_on??c.endsOn} className="block w-full rounded border bg-background p-2"/></label><label className="sm:col-span-2">Performance evidence for {a.key}<textarea required name={'evidence-'+i} maxLength={2000} className="block w-full rounded border bg-background p-2"/></label></fieldset>;})}
   <p>For prospective treatment, start remaining service after the revision date and enter zero progress. Percentage-complete estimates require a new dated revision when progress changes. Milestones use 0% or 100% with transfer evidence.</p>
  </FinanceActionForm></details>:null}
  {canWrite&&latest?<details><summary>Bill revised consideration</summary><FinanceActionForm title="Request supplemental contract invoice" fields={[{name:'number',label:'Supplemental invoice number'},{name:'date',label:'Supplemental invoice date',type:'date'},{name:'due',label:'Supplemental invoice due date',type:'date'},{name:'amount',label:'Supplemental net amount'},{name:'reason',label:'Supplemental billing evidence'}]} submit={(v,key)=>{const tax=readTaxAssessment(v);return requestFinance(entity,'CONTRACT_SUPPLEMENT_BILL',{cycle_id:c.id,number:v.number,issue_date:v.date,due_date:v.due,amount:v.amount,...(tax?{tax}:{})},v.reason,key);}}><TaxAssessmentFields optional/></FinanceActionForm></details>:null}
  {c.supplements.map(s=><p key={s.id}>Supplemental invoice {s.invoiceId} · {s.date} · Net {s.amount}</p>)}
 </section>;
}
