import assert from 'node:assert/strict';
import test from 'node:test';
import {financeDatabase,ids,reviewer,actor,call} from './helpers/finance-workflows.mjs';
const deferred='30000000-0000-4000-8000-000000000097',unbilled='30000000-0000-4000-8000-000000000098',liability='30000000-0000-4000-8000-000000000099';let seq=0;
async function approve(db,kind,payload){await actor(db,ids.adminA);const req=await call(db,'request_finance_action',ids.entityA,kind,payload,'Synthetic finance source evidence','revision-'+(++seq));await actor(db,reviewer);const result=await call(db,'decide_finance_action',req,'APPROVE','Independent accounting review');await actor(db,ids.adminA);return {req,...result};}
const report=(db,contract,day='2026-01-31')=>call(db,'get_contract_finance',contract,day);
const obligation=(key,amount,overrides={})=>({key,amount,treatment:'CATCH_UP',method:'PERCENT_COMPLETE',starts_on:'2026-01-01',ends_on:'2026-01-31',progress:'50',evidence:'Synthetic progress assessment with revised expected effort',...overrides});
const revision=(cycle,date,price,obligations)=>({cycle_id:cycle,date,price,reference:'MOD-'+(++seq),policy_evidence:'Reviewed distinctness and allocation assessment',variable_consideration:'Reviewed enforceable consideration and constraint; synthetic contract',obligations});
async function database(bundle=false){const db=await financeDatabase();await db.exec(`RESET ROLE;INSERT INTO public.accounts VALUES('${deferred}','${ids.orgA}','2397','Revision deferred','liability',true),('${unbilled}','${ids.orgA}','1397','Revision unbilled','asset',true),('${liability}','${ids.orgA}','2398','Revision credits','liability',true);SET ROLE authenticated`);await approve(db,'CUSTOMER_CREDIT_POLICY',{liability_account_id:liability});
 const {contractId}=await approve(db,'CONTRACT_CREATE',{customer_id:ids.customerA,reference:'REVISED',kind:'FIXED',starts_on:'2026-01-01',ends_on:'2026-01-31',cycle_months:0,price:'310.00',unit_price:'0.00',timezone:'UTC',deferred_account_id:deferred,unbilled_account_id:unbilled,obligations:bundle?[{key:'access',description:'Access',standalone_price:'155.00',method:'DAILY'},{key:'service',description:'Service',standalone_price:'155.00',method:'DAILY'}]:[{key:'service',description:'Service',standalone_price:'310.00',method:'DAILY'}]});const cycle=(await report(db,contractId)).cycles[0].id;const {invoiceId}=await approve(db,'CONTRACT_BILL',{cycle_id:cycle,number:'BASE',issue_date:'2026-01-01',due_date:'2026-01-31'});return {db,contract:contractId,cycle,invoice:invoiceId};}
test('reviewed progress revisions retain negative catch-up, dated controls and a later positive estimate',async()=>{const {db,contract,cycle}=await database();try{
 await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-10',evidence:[]});const p=revision(cycle,'2026-01-11','310.00',[obligation('service','310.00',{progress:'20'})]);const corrected=await approve(db,'CONTRACT_REVISE',p);assert.equal(corrected.amount,'-38.00');let r=await report(db,contract,'2026-01-11');assert.deepEqual([r.billed,r.recognized,r.deferred,r.unbilled],['310.00','62.00','248.00','0.00']);assert.ok(r.controls.every(x=>x.variance==='0.00'));assert.equal((await report(db,contract,'2026-01-10')).recognized,'100.00');
 await actor(db,reviewer);assert.equal((await call(db,'decide_finance_action',corrected.req,'APPROVE','Independent accounting review')).revisionId,corrected.revisionId);await actor(db,ids.adminA);
 const next=await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-20','310.00',[obligation('service','310.00',{progress:'80'})]));assert.equal(next.amount,'186.00');r=await report(db,contract,'2026-01-20');assert.equal(r.recognized,'248.00');assert.equal(r.cycles[0].revisions.length,2);
 await assert.rejects(call(db,'reverse_posted_journal',corrected.journalId,'2026-01-21','Invalid standalone reversal','standalone-revision'),/contract workflow|subsequent approved revision/);
 await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-02-01','310.00',[obligation('service','310.00',{progress:'100'})]));r=await report(db,contract,'2026-02-01');assert.equal(r.recognized,'310.00');assert.equal(r.deferred,'0.00');
}finally{await db.close();}});
test('mixed prospective and catch-up obligations allocate every cent and continue daily recognition',async()=>{const {db,contract,cycle}=await database(true);try{
 await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-10',evidence:[]});const revised=await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-11','310.00',[obligation('access','200.00',{treatment:'PROSPECTIVE',method:'DAILY',starts_on:'2026-01-12',progress:'0'}),obligation('service','110.00',{progress:'50'})]));assert.equal(revised.amount,'5.00');let r=await report(db,contract,'2026-01-11');assert.equal(r.recognized,'105.00');await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-21',evidence:[]});r=await report(db,contract,'2026-01-21');assert.equal(r.recognized,'180.00');assert.ok(r.controls.every(x=>x.variance==='0.00'));
 await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-31','310.00',[obligation('access','200.00',{progress:'100'}),obligation('service','110.00',{progress:'100'})]));assert.equal((await report(db,contract)).recognized,'310.00');
}finally{await db.close();}});
test('additional consideration recognizes unbilled revenue and supplemental billing clears the correct asset',async()=>{const {db,contract,cycle}=await database();try{
 await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-10',evidence:[]});const r=await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-11','500.00',[obligation('service','500.00',{progress:'80'})]));assert.equal(r.amount,'300.00');let current=await report(db,contract,'2026-01-11');assert.deepEqual([current.recognized,current.deferred,current.unbilled],['400.00','0.00','90.00']);
 const supplement=await approve(db,'CONTRACT_SUPPLEMENT_BILL',{cycle_id:cycle,number:'SUPPLEMENT',issue_date:'2026-01-12',due_date:'2026-01-31',amount:'190.00'});current=await report(db,contract,'2026-01-12');assert.deepEqual([current.billed,current.recognized,current.deferred,current.unbilled],['500.00','400.00','100.00','0.00']);assert.ok(current.controls.every(x=>x.variance==='0.00'));assert.equal(current.cycles[0].supplements[0].invoiceId,supplement.invoiceId);
 await assert.rejects(approve(db,'CONTRACT_SUPPLEMENT_BILL',{cycle_id:cycle,number:'EXCESS',issue_date:'2026-01-13',due_date:'2026-01-31',amount:'0.01'}),/exceeds/);
 const line=(await call(db,'get_customer_adjustments',ids.entityA,'2026-01-12')).invoices.find(i=>i.id===supplement.invoiceId).lines[0].id;await approve(db,'CUSTOMER_CREDIT',{invoice_id:supplement.invoiceId,reference:'SUPPLEMENT-CONCESSION',date:'2026-01-13',lines:[{line_id:line,amount:'100.00'}]});current=await report(db,contract,'2026-01-13');assert.deepEqual([current.billed,current.recognized,current.deferred],['400.00','320.00','80.00']);assert.ok(current.controls.every(x=>x.variance==='0.00'));
}finally{await db.close();}});
test('revision approvals reject self-review, stale billing state, unbalanced allocations and cross-tenant access',async()=>{const {db,cycle}=await database();try{
 const p=revision(cycle,'2026-01-11','310.00',[obligation('service','310.00')]);const req=await call(db,'request_finance_action',ids.entityA,'CONTRACT_REVISE',p,'Synthetic assessment','pending-revision');await assert.rejects(call(db,'decide_finance_action',req,'APPROVE','Self approval'),/independent/);await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-10',evidence:[]});await actor(db,reviewer);await assert.rejects(call(db,'decide_finance_action',req,'APPROVE','Stale approval'),/changed/);await actor(db,ids.adminA);
 await assert.rejects(approve(db,'CONTRACT_REVISE',{...p,price:'309.00'}),/overbilled|equal/);await assert.rejects(approve(db,'CONTRACT_REVISE',{...p,obligations:[obligation('service','309.99')]}),/equal/);
 await actor(db,ids.adminB);await assert.rejects(call(db,'request_finance_action',ids.entityA,'CONTRACT_REVISE',p,'Cross tenant','cross-revision'),/scope|entity|unavailable/);await actor(db,ids.adminA);await assert.rejects(db.exec('SELECT * FROM public.finance_revenue_revisions'),/permission denied/);await assert.rejects(call(db,'revenue_revision_preview',ids.entityA,p),/permission denied/);
}finally{await db.close();}});
test('revenue reports and close detect a missing retained revision or a changed progress journal',async()=>{const {db,contract,cycle}=await database();try{
 const revisionId=(await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-11','310.00',[obligation('service','310.00')]))).revisionId;await db.exec('RESET ROLE;SET session_replication_role=replica');await db.query("UPDATE public.finance_revenue_revisions SET amount=amount+0.01 WHERE id=$1",[revisionId]);await db.exec('SET session_replication_role=origin;SET ROLE authenticated');await assert.rejects(report(db,contract),/approval|catch-up/);await assert.rejects(call(db,'get_finance_close_check',ids.entityA,'2026-01-01','2026-01-31'),/approval|catch-up/);
}finally{await db.close();}});
test('credits against partially unbilled revised revenue move the asset and retain receivable reconciliation',async()=>{const {db,contract,cycle,invoice}=await database();try{
 await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-11','500.00',[obligation('service','500.00',{progress:'80'})]));const line=(await call(db,'get_customer_adjustments',ids.entityA,'2026-01-11')).invoices.find(i=>i.id===invoice).lines[0].id;
 await approve(db,'CUSTOMER_CREDIT',{invoice_id:invoice,reference:'UNBILLED-CONCESSION',date:'2026-01-12',lines:[{line_id:line,amount:'100.00'}]});const r=await report(db,contract,'2026-01-12');assert.deepEqual([r.billed,r.recognized,r.deferred,r.unbilled],['210.00','320.00','0.00','110.00']);assert.ok(r.controls.every(x=>x.variance==='0.00'));
 await approve(db,'CONTRACT_SUPPLEMENT_BILL',{cycle_id:cycle,number:'UNBILLED-SUPPLEMENT',issue_date:'2026-01-13',due_date:'2026-01-31',amount:'190.00'});assert.equal((await report(db,contract,'2026-01-13')).deferred,'80.00');
}finally{await db.close();}});
test('a zero-net reallocation preserves an approval without manufacturing a journal',async()=>{const {db,contract,cycle}=await database(true);try{
 await approve(db,'CONTRACT_RECOGNIZE',{cycle_id:cycle,as_of:'2026-01-10',evidence:[]});const revised=await approve(db,'CONTRACT_REVISE',revision(cycle,'2026-01-11','310.00',[obligation('access','200.00',{progress:'25'}),obligation('service','110.00',{treatment:'PROSPECTIVE',method:'DAILY',starts_on:'2026-01-12',progress:'0'})]));assert.equal(revised.amount,'0.00');assert.equal(revised.journalId,null);assert.equal((await report(db,contract,'2026-01-11')).recognized,'100.00');
}finally{await db.close();}});
