import assert from 'node:assert/strict';
import test from 'node:test';
import {financeDatabase,ids,reviewer,actor,call} from './helpers/finance-workflows.mjs';
import {loadTypescript} from './helpers/load-typescript.mjs';
const {parseConsolidation}=await loadTypescript('../../src/lib/groupFinance.ts');
const sub='40000000-0000-4000-8000-000000000090',eur='40000000-0000-4000-8000-000000000091';
const asset='30000000-0000-4000-8000-000000000090',capital='30000000-0000-4000-8000-000000000091',retained='30000000-0000-4000-8000-000000000092',cta='30000000-0000-4000-8000-000000000093',accrued='30000000-0000-4000-8000-000000000094',investment='30000000-0000-4000-8000-000000000095',dueFrom='30000000-0000-4000-8000-000000000096',dueTo='30000000-0000-4000-8000-000000000097';let seq=0;
const closeAttest={bank_sources_complete:true,usage_and_contracts_complete:true,unrecorded_liabilities_reviewed:true,asset_policies_reviewed:true,tax_and_opening_balances_reviewed:true};
const groupAttest={ownership_and_periods_reviewed:true,fx_policy_reviewed:true,eliminations_reviewed:true};
async function database(){const db=await financeDatabase();await db.exec(`RESET ROLE;INSERT INTO public.entities(id,org_id,name,currency) VALUES('${sub}','${ids.orgA}','US subsidiary','USD'),('${eur}','${ids.orgA}','EUR subsidiary','EUR');INSERT INTO public.accounts VALUES('${asset}','${ids.orgA}','1950','Other asset','asset',true),('${capital}','${ids.orgA}','3000','Capital','equity',true),('${retained}','${ids.orgA}','3100','Retained earnings','equity',true),('${cta}','${ids.orgA}','3900','Group CTA','equity',true),('${accrued}','${ids.orgA}','2450','Accrued liabilities','liability',true),('${investment}','${ids.orgA}','1960','Investment','asset',true),('${dueFrom}','${ids.orgA}','1360','Intercompany due from','asset',true),('${dueTo}','${ids.orgA}','2360','Intercompany due to','liability',true);SET ROLE authenticated`);for(const e of [ids.entityA,sub,eur])await call(db,'create_accounting_period',e,'2025-01-01','2025-12-31','group-year-'+e);return db;}
const post=(db,entity,date,debit,credit,amount)=>call(db,'post_manual_journal',entity,'GROUP-SOURCE-'+(++seq),date,'Synthetic source',[{account_id:debit,debit:amount,credit:'0.00'},{account_id:credit,debit:'0.00',credit:amount}],'group-source-'+seq);
async function request(db,kind,payload,entity=ids.entityA){await actor(db,ids.adminA);return call(db,'request_finance_action',entity,kind,payload,'Verified group accounting policy','group-request-'+(++seq));}
async function approve(db,kind,payload,entity=ids.entityA){const id=await request(db,kind,payload,entity);await actor(db,reviewer);const result=await call(db,'decide_finance_action',id,'APPROVE','Independent group accounting review');await actor(db,ids.adminA);return result;}
const group=async(db,member)=>approve(db,'GROUP_CREATE',{reference:'GROUP-'+(++seq),name:'Synthetic reporting group',currency:'USD',starts_on:'2025-01-01',member_ids:[ids.entityA,member],cta_account_id:cta,ownership_basis:'WHOLLY_OWNED'}).then(r=>r.groupId);
const close=(db,e)=>approve(db,'FISCAL_YEAR_CLOSE',{starts_on:'2025-01-01',ends_on:'2025-12-31',retained_account_id:retained,attestations:closeAttest},e);
const preview=async(db,g,rates=[])=>parseConsolidation(await call(db,'get_consolidation_report',g,'2025-01-01','2025-12-31',rates),{group:g,from:'2025-01-01',through:'2025-12-31'});
const final=(g,rates=[])=>({group_id:g,starts_on:'2025-01-01',ends_on:'2025-12-31',rates,attestations:groupAttest});
async function quotes(db,g,overrides={}){const r=await call(db,'get_consolidation_rate_requirements',g,'2025-01-01','2025-12-31');return r.quotes.map(q=>({...q,rate:overrides[q.kind+':'+q.date]??(q.kind==='HISTORICAL'?'1.10':q.kind==='AVERAGE'?(q.date==='2025-01-01'?'1.20':'1.25'):(q.date==='2025-12-31'?'1.30':'1.10'))}));}

const nci='30000000-0000-4000-8000-000000000098',parentEquity='30000000-0000-4000-8000-000000000099';
async function controlled(db,member,percentage='80'){
 await db.exec(`RESET ROLE;INSERT INTO public.accounts VALUES('${nci}','${ids.orgA}','3950','Noncontrolling interests','equity',true),('${parentEquity}','${ids.orgA}','3940','Parent equity attribution','equity',true);SET ROLE authenticated`);
 return approve(db,'GROUP_CREATE',{reference:'CONTROLLED-'+(++seq),name:'Controlled group',currency:'USD',starts_on:'2025-01-01',member_ids:[ids.entityA,member],cta_account_id:cta,ownership_basis:'CONTROLLED',nci_account_id:nci,parent_equity_account_id:parentEquity,ownership:[{entity_id:ids.entityA,percentage:'100',basis:'PARENT',evidence:'Synthetic reporting parent'},{entity_id:member,percentage,basis:'ORDINARY_VOTING_SHARES',evidence:'Synthetic direct ordinary-share voting ownership, constant throughout period'}]}).then(r=>r.groupId);
}
const raw=async(db,g,rates=[])=>parseConsolidation(await call(db,'get_consolidation_report',g,'2025-01-01','2025-12-31',rates),{group:g,from:'2025-01-01',through:'2025-12-31'});
test('majority-owned consolidation preserves full books and allocates earnings and equity separately',async()=>{const db=await database();try{
 await post(db,ids.entityA,'2025-01-01',asset,ids.revenueA,'300.00');await post(db,sub,'2025-01-02',asset,ids.revenueA,'100.00');await post(db,sub,'2025-01-03',ids.expenseA,accrued,'20.00');const g=await controlled(db,sub);let r=await raw(db,g);assert.equal(r.netIncome,'380.00');const bad=structuredClone(r);bad.ownership.members[1].noncontrollingIncome='16.01';assert.throws(()=>parseConsolidation(bad,{group:g,from:'2025-01-01',through:'2025-12-31'}),/attribution/);assert.equal(r.ownership.noncontrollingIncome,'16.00');assert.equal(r.ownership.parentIncome,'364.00');assert.equal(r.ownership.noncontrollingEquity,'16.00');assert.equal(r.rows.find(x=>x.accountId===nci).closing,'-16.00');assert.equal(r.rows.find(x=>x.accountId===asset).closing,'400.00');
 await close(db,ids.entityA);await close(db,sub);r=await raw(db,g);assert.equal(r.canFinalize,true);const saved=await approve(db,'GROUP_CONSOLIDATE',final(g));assert.equal((await call(db,'get_approved_consolidation',saved.consolidationId)).report.ownership.parentIncome,'364.00');
}finally{await db.close();}});
test('noncontrolling losses may exceed contributed equity without being silently assigned to the parent',async()=>{const db=await database();try{
 await post(db,ids.entityA,'2025-01-01',asset,ids.revenueA,'300.00');await post(db,sub,'2025-01-02',ids.expenseA,accrued,'200.00');const g=await controlled(db,sub);const r=await raw(db,g);assert.equal(r.netIncome,'100.00');assert.equal(r.ownership.noncontrollingIncome,'-40.00');assert.equal(r.ownership.parentIncome,'140.00');assert.equal(r.ownership.noncontrollingEquity,'-40.00');assert.equal(r.rows.find(x=>x.accountId===nci).closing,'40.00');
}finally{await db.close();}});
test('foreign subsidiary ownership allocates closing net assets, translated earnings and CTA independently',async()=>{const db=await database();try{
 await post(db,ids.entityA,'2025-01-01',asset,ids.revenueA,'300.00');await post(db,eur,'2025-01-01',asset,capital,'100.00');await post(db,eur,'2025-01-02',asset,ids.revenueA,'100.00');await post(db,eur,'2025-12-01',ids.expenseA,accrued,'20.00');const g=await controlled(db,eur),rates=await quotes(db,g);let r=await raw(db,g,rates);assert.equal(r.netIncome,'395.00');assert.equal(r.ownership.noncontrollingIncome,'19.00');assert.equal(r.ownership.noncontrollingEquity,'46.80');assert.equal(r.ownership.noncontrollingTranslation,'-5.80');assert.equal(r.ownership.parentTranslation,'-23.20');await close(db,ids.entityA);await close(db,eur);r=await raw(db,g,await quotes(db,g));assert.equal(r.ownership.noncontrollingIncome,'19.00');assert.equal(r.ownership.noncontrollingEquity,'46.80');
}finally{await db.close();}});
test('reviewed upstream adjustment attribution changes subsidiary NCI while parent-only adjustments do not',async()=>{const db=await database();try{
 const parentSource=await post(db,ids.entityA,'2025-01-01',asset,ids.revenueA,'300.00');const subSource=await post(db,sub,'2025-01-02',asset,ids.revenueA,'100.00');await post(db,sub,'2025-01-03',ids.expenseA,accrued,'20.00');const g=await controlled(db,sub);
 const payload={group_id:g,date:'2025-01-04',reference:'UPSTREAM',lines:[{account_id:ids.revenueA,debit:'30.00',credit:'0.00'},{account_id:asset,debit:'0.00',credit:'30.00'}],source_journals:[subSource]};await assert.rejects(approve(db,'GROUP_ADJUSTMENT',payload),/attribution|member whose/);const adjusted=await approve(db,'GROUP_ADJUSTMENT',{...payload,attribution_entity:sub,attribution_evidence:'Synthetic upstream unrealized profit belongs to seller subsidiary'});let r=await raw(db,g);assert.equal(r.netIncome,'350.00');assert.equal(r.ownership.noncontrollingIncome,'10.00');assert.equal(r.ownership.parentIncome,'340.00');assert.equal(r.ownership.noncontrollingEquity,'10.00');
 await approve(db,'GROUP_ADJUSTMENT',{...payload,reference:'PARENT-ADJUSTMENT',source_journals:[parentSource],attribution_entity:ids.entityA,attribution_evidence:'Synthetic adjustment affects parent only'});r=await raw(db,g);assert.equal(r.netIncome,'320.00');assert.equal(r.ownership.noncontrollingIncome,'10.00');await approve(db,'GROUP_ADJUSTMENT_REVERSE',{adjustment_id:adjusted.adjustmentId,date:'2025-01-05'});assert.equal((await raw(db,g)).ownership.noncontrollingIncome,'16.00');
}finally{await db.close();}});
test('ownership percentages preserve rounding residuals in the parent and reject unsupported control claims',async()=>{const db=await database();try{
 await post(db,sub,'2025-01-02',asset,ids.revenueA,'0.05');const g=await controlled(db,sub,'66.666667');const r=await raw(db,g);assert.equal(r.ownership.noncontrollingIncome,'0.02');assert.equal(r.ownership.parentIncome,'0.03');await actor(db,ids.adminB);await assert.rejects(raw(db,g),/unavailable/);await actor(db,ids.adminA);
 const t=(await db.query('SELECT terms FROM public.finance_groups WHERE id=$1',[g])).rows[0].terms;await assert.rejects(approve(db,'GROUP_CREATE',{...t,reference:'NO-CONTROL',ownership:t.ownership.map(x=>x.entity_id===sub?{...x,percentage:'50'}:x)}),/majority/);await assert.rejects(approve(db,'GROUP_CREATE',{...t,reference:'DUP-OWNER',ownership:[t.ownership[0],t.ownership[0]]}),/unique|every/);await assert.rejects(approve(db,'GROUP_CREATE',{...t,reference:'MISSING-OWNER',ownership:t.ownership.map(x=>x.entity_id===sub?{percentage:'80',basis:x.basis,evidence:x.evidence}:x)}),/unique|majority/);await assert.rejects(approve(db,'GROUP_CREATE',{...t,reference:'AMBIGUOUS-PERCENT',ownership:t.ownership.map(x=>x.entity_id===sub?{...x,percentage:'080'}:x)}),/unique|majority/);
}finally{await db.close();}});
test('approved ownership snapshots retain their original attribution after a controlled reopening',async()=>{const db=await database();try{
 await post(db,sub,'2025-01-02',asset,ids.revenueA,'100.00');const g=await controlled(db,sub);const parentClose=await close(db,ids.entityA);await close(db,sub);const approved=await approve(db,'GROUP_CONSOLIDATE',final(g));await approve(db,'GROUP_REOPEN',{consolidation_id:approved.consolidationId});await approve(db,'FISCAL_YEAR_REOPEN',{close_id:parentClose.closeId});const old=await call(db,'get_approved_consolidation',approved.consolidationId);assert.equal(old.report.ownership.noncontrollingIncome,'20.00');assert.equal(old.active,false);assert.equal(old.sourceChanged,true);
 await db.exec('RESET ROLE;SET session_replication_role=replica');await db.query("UPDATE public.finance_groups SET terms=jsonb_set(terms,'{ownership,1,percentage}','\"90\"') WHERE id=$1",[g]);await db.exec('SET session_replication_role=origin;SET ROLE authenticated');await assert.rejects(raw(db,g),/lineage|approval/);
}finally{await db.close();}});
