import assert from 'node:assert/strict';
import test from 'node:test';
import {loadTypescript} from './helpers/load-typescript.mjs';
const {parseFinancialStatements,financialStatementCsv}=await loadTypescript('../../src/lib/financialStatements.ts');
import {financeDatabase,ids,reviewer,actor,call} from './helpers/finance-workflows.mjs';
const bank2='30000000-0000-4000-8000-000000000080',capital='30000000-0000-4000-8000-000000000081',fixed='30000000-0000-4000-8000-000000000082',loan='30000000-0000-4000-8000-000000000083';let seq=0;
async function request(db,kind,payload){await actor(db,ids.adminA);return call(db,'request_finance_action',ids.entityA,kind,payload,'Reviewed statement presentation','statements-'+(++seq));}
async function approve(db,kind,payload){const id=await request(db,kind,payload);await actor(db,reviewer);const r=await call(db,'decide_finance_action',id,'APPROVE','Independent cash and presentation review');await actor(db,ids.adminA);return r;}
async function setup(){const db=await financeDatabase();await db.exec(`RESET ROLE;INSERT INTO public.accounts VALUES('${bank2}','${ids.orgA}','1020','Savings','asset',true),('${capital}','${ids.orgA}','3000','Capital','equity',true),('${fixed}','${ids.orgA}','1600','Equipment','asset',true),('${loan}','${ids.orgA}','2400','Loan','liability',true);SET ROLE authenticated`);await call(db,'create_cash_register',ids.entityA,ids.cashA,'Operating bank');await call(db,'create_cash_register',ids.entityA,bank2,'Savings bank');return db;}
async function policyPayload(db){const ctx=await call(db,'get_statement_policy_context',ids.entityA);const sections={[ids.cashA]:'CASH',[bank2]:'CASH',[capital]:'CAPITAL',[fixed]:'NONCURRENT_ASSETS',[loan]:'NONCURRENT_LIABILITIES',[ids.arA]:'TRADE_RECEIVABLES',[ids.apA]:'CURRENT_LIABILITIES',[ids.revenueA]:'REVENUE',[ids.expenseA]:'OPERATING_EXPENSES'};return {group_id:null,expected_version:ctx.policy?.version??0,cash_accounts:ctx.cashAccounts,mappings:Object.entries(sections).map(([account_id,section])=>({account_id,section}))};}
async function policy(db){return (await approve(db,'STATEMENT_POLICY',await policyPayload(db))).policyId;}
const post=(db,date,lines)=>call(db,'post_manual_journal',ids.entityA,'CF-'+(++seq),date,'Synthetic classified cash',lines.map(([account_id,debit,credit])=>({account_id,debit,credit})),'cf-post-'+seq);
const pair=(db,date,debit,credit,amount)=>post(db,date,[[debit,amount,'0.00'],[credit,'0.00',amount]]);
const report=async db=>parseFinancialStatements(await call(db,'get_entity_financial_statements',ids.entityA,'2026-01-01','2026-06-30'),{entity:ids.entityA,from:'2026-01-01',through:'2026-06-30'});
const item=(s,allocations)=>({line_id:s.lineId,expected_version:s.version,allocations:allocations.map(([category,amount])=>({category,amount}))});
test('approved cash splits and paired transfers reconcile mapped statements without concealing unclassified cash',async()=>{
 const db=await setup();try{
  const initial=await policyPayload(db);initial.mappings.find(m=>m.account_id===bank2).section='RESTRICTED_CASH_NONCURRENT';const p=(await approve(db,'STATEMENT_POLICY',initial)).policyId;await pair(db,'2026-01-01',ids.cashA,capital,'1000.00');await pair(db,'2026-02-01',ids.cashA,ids.revenueA,'400.00');
  await post(db,'2026-03-01',[[ids.expenseA,'50.00','0.00'],[fixed,'100.00','0.00'],[ids.cashA,'0.00','150.00']]);await pair(db,'2026-04-01',bank2,ids.cashA,'200.00');await pair(db,'2026-05-01',ids.cashA,loan,'300.00');
  let r=await report(db);assert.equal(r.complete,false);assert.equal(r.statements.complete,true);assert.equal(r.cashFlow.unclassifiedCount,6);assert.equal(r.cashFlow.closingCash,'1550.00');assert.equal(r.statements.netIncome,'350.00');assert.equal(r.statements.assets,'1650.00');assert.equal(r.statements.sections.find(s=>s.section==='RESTRICTED_CASH_NONCURRENT').total,'200.00');
  const sources=r.cashFlow.sources;const transfer=sources.filter(s=>s.date==='2026-04-01');await assert.rejects(approve(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:[item(transfer[0],[['TRANSFER','200.00']])]}),/offset exactly/);
  const allocations=sources.map(s=>item(s,s.date==='2026-01-01'?[['EQUITY','1000.00']]:s.date==='2026-02-01'?[['CUSTOMER_RECEIPTS','400.00']]:s.date==='2026-03-01'?[['SUPPLIER_EMPLOYEE_PAYMENTS','50.00'],['CAPITAL_EXPENDITURES','100.00']]:s.date==='2026-04-01'?[['TRANSFER','200.00']]:[['BORROWINGS','300.00']]));
  await approve(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:allocations});r=await report(db);assert.equal(r.complete,true);assert.equal(r.cashFlow.classifiedMovement,'1550.00');assert.equal(r.cashFlow.transferNet,'0.00');assert.equal(r.cashFlow.categories.find(c=>c.category==='SUPPLIER_EMPLOYEE_PAYMENTS').net,'-50.00');assert.equal(r.cashFlow.categories.find(c=>c.category==='CAPITAL_EXPENDITURES').net,'-100.00');assert.equal(r.statements.unclosedEarnings,'350.00');assert.match(financialStatementCsv(r,'Synthetic statements'),/Capital expenditure/);const corrupted=structuredClone(r);corrupted.cashFlow.sources[0].amount='1001.00';assert.throws(()=>parseFinancialStatements(corrupted,{entity:ids.entityA,from:'2026-01-01',through:'2026-06-30'}),/complete ledger line/);
  const s=r.cashFlow.sources.find(s=>s.date==='2026-03-01');await assert.rejects(approve(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:[item(s,[['OTHER_OPERATING','149.99']])]}),/exactly equal/);
  const transferNow=r.cashFlow.sources.filter(s=>s.date==='2026-04-01');await assert.rejects(approve(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:[item(transferNow[0],[['OTHER_OPERATING','200.00']])]}),/every active side/);
  const changed=await request(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:[item(s,[['OTHER_OPERATING','150.00']])]});await approve(db,'CASH_FLOW_CLASSIFY',{policy_id:p,items:[item(s,[['SUPPLIER_EMPLOYEE_PAYMENTS','60.00'],['CAPITAL_EXPENDITURES','90.00']])]});await actor(db,reviewer);await assert.rejects(call(db,'decide_finance_action',changed,'APPROVE','Old classification'),/changed/);await actor(db,ids.adminA);
  assert.equal((await report(db)).cashFlow.sources.find(x=>x.lineId===s.lineId).version,2);
  await db.exec('SET ROLE service_role');await assert.rejects(db.exec('UPDATE public.finance_cash_classifications SET version=3'),/permission denied/);await db.exec('SET ROLE authenticated');await actor(db,ids.adminB);await assert.rejects(report(db),/unavailable|accessible|not found/);assert.equal((await db.query('SELECT * FROM public.finance_statement_policies')).rows.length,0);
 }finally{await db.close();}
});
test('statement mappings require complete bank coverage and invalidate stale policy approvals',async()=>{
 const db=await setup();try{
  const bad=await policyPayload(db);bad.cash_accounts=[ids.cashA];await assert.rejects(approve(db,'STATEMENT_POLICY',bad),/each registered/);
  await policy(db);await pair(db,'2026-02-01',fixed,capital,'100.00');let payload=await policyPayload(db);payload.mappings=payload.mappings.filter(x=>x.account_id!==fixed);payload.mappings.find(x=>x.account_id===bank2).section='RESTRICTED_CASH_NONCURRENT';await approve(db,'STATEMENT_POLICY',payload);let r=await report(db);assert.equal(r.complete,false);assert.equal(r.statements.unmapped[0].accountId,fixed);
  payload=await policyPayload(db);const pending=await request(db,'STATEMENT_POLICY',payload);await approve(db,'STATEMENT_POLICY',payload);await actor(db,reviewer);await assert.rejects(call(db,'decide_finance_action',pending,'APPROVE','Stale mapping'),/changed/);await actor(db,ids.adminA);
  r=await report(db);assert.equal(r.complete,true);assert.equal(r.statements.policyVersion,3);assert.equal((await call(db,'get_finance_close_check',ids.entityA,'2026-01-01','2026-06-30')).statementControls.complete,true);
  const invalid=await policyPayload(db);invalid.mappings.find(m=>m.account_id===ids.revenueA).section='CASH';await assert.rejects(approve(db,'STATEMENT_POLICY',invalid),/account type/);
 }finally{await db.close();}
});
test('approved native statements preserve income through fiscal closing and retain noncash balance-sheet movements',async()=>{
 const db=await setup();try{
  await call(db,'create_accounting_period',ids.entityA,'2025-01-01','2025-12-31','statement-old-year');await policy(db);await pair(db,'2025-03-01',fixed,ids.revenueA,'250.00');
  for(const register of (await db.query('SELECT id FROM public.cash_registers')).rows){const statement=await call(db,'import_cash_statement',register.id,{reference:'Zero activity '+register.id,starts_on:'2025-01-01',ends_on:'2025-12-31',opening:'0.00',closing:'0.00',lines:[]},'zero-bank-'+register.id);const cash=await call(db,'get_cash_reconciliation',statement);const review=await call(db,'request_cash_review',statement,'CLOSE','Accepted zero bank activity',cash.revision);await actor(db,reviewer);await call(db,'decide_cash_review',review,'APPROVE','Independent zero bank source');await actor(db,ids.adminA);}
  const read=async()=>parseFinancialStatements(await call(db,'get_entity_financial_statements',ids.entityA,'2025-01-01','2025-12-31'),{entity:ids.entityA,from:'2025-01-01',through:'2025-12-31'});let r=await read();assert.equal(r.statements.netIncome,'250.00');assert.equal(r.statements.unclosedEarnings,'250.00');assert.equal(r.cashFlow.classifiedMovement,'0.00');
  const closed=await approve(db,'FISCAL_YEAR_CLOSE',{starts_on:'2025-01-01',ends_on:'2025-12-31',retained_account_id:capital,attestations:{bank_sources_complete:true,usage_and_contracts_complete:true,unrecorded_liabilities_reviewed:true,asset_policies_reviewed:true,tax_and_opening_balances_reviewed:true}});r=await read();assert.equal(r.complete,true);assert.equal(r.statements.netIncome,'250.00');assert.equal(r.statements.unclosedEarnings,'0.00');assert.equal(r.statements.recordedEquity,'250.00');await approve(db,'FISCAL_YEAR_REOPEN',{close_id:closed.closeId});assert.equal((await read()).statements.unclosedEarnings,'250.00');
 }finally{await db.close();}
});
