import assert from 'node:assert/strict';
import test from 'node:test';
import {financeDatabase,ids,reviewer,actor,call} from './helpers/finance-workflows.mjs';
const policy={receivable_account:'30000000-0000-4000-8000-000000000101',payable_account:'30000000-0000-4000-8000-000000000102',unrealized_gain:'30000000-0000-4000-8000-000000000103',unrealized_loss:'30000000-0000-4000-8000-000000000104',realized_gain:'30000000-0000-4000-8000-000000000105',realized_loss:'30000000-0000-4000-8000-000000000106'};
const taxPolicy={sales_account:'30000000-0000-4000-8000-000000000107',recoverable_account:'30000000-0000-4000-8000-000000000108',expense_account:'30000000-0000-4000-8000-000000000109'};let seq=0;
async function approve(db,kind,payload){await actor(db,ids.adminA);const req=await call(db,'request_finance_action',ids.entityA,kind,payload,'Synthetic original accounting evidence','fx-'+(++seq));await actor(db,reviewer);const result=await call(db,'decide_finance_action',req,'APPROVE','Independent currency review');await actor(db,ids.adminA);return {req,...result};}
const report=(db,date='2026-01-31')=>call(db,'get_foreign_currency_report',ids.entityA,date);
const document=(overrides={})=>({kind:'RECEIVABLE',party_id:ids.customerA,number:'FX-'+(++seq),date:'2026-01-01',due_date:'2026-01-20',currency:'EUR',net_amount:'100.00',rate:'1.10',rate_source:'Synthetic dated rate fixture, not a market quote',evidence:'Synthetic enforceable foreign invoice',offset_account:ids.revenueA,tax_explanation:'Synthetic non-taxable transaction assessment',...overrides});
const event=(id,date,overrides={})=>({document_id:id,date,reference:'CONFIRM-'+(++seq),evidence:'Synthetic source confirmation',...overrides});
const remeasure=(db,id,date,rate)=>approve(db,'FX_REMEASURE',event(id,date,{rate,rate_source:'Synthetic closing rate'}));
const settle=(db,id,date,foreign_amount,rate,cash_amount)=>approve(db,'FX_SETTLE',event(id,date,{foreign_amount,rate,cash_amount,cash_account:ids.cashA,rate_source:'Synthetic executed bank rate'}));
const balance=(db,account,date)=>db.query("SELECT coalesce(sum(l.debit-l.credit),0)::numeric(38,2)::text AS value FROM public.journal_lines l JOIN public.journal_entries j ON j.id=l.journal_entry_id WHERE j.entity_id=$1 AND l.account_id=$2 AND j.entry_date<=$3",[ids.entityA,account,date]).then(r=>r.rows[0].value);
async function database(){const db=await financeDatabase();await db.exec('RESET ROLE');for(const [key,id] of Object.entries({...policy,...taxPolicy})){const type=key==='receivable_account'||key==='recoverable_account'?'asset':key==='payable_account'||key==='sales_account'?'liability':key.endsWith('gain')?'revenue':'expense';await db.query('INSERT INTO public.accounts VALUES($1,$2,$3,$4,$5,true)',[id,ids.orgA,'FX'+id.slice(-3),key,type]);}await db.exec('SET ROLE authenticated');await approve(db,'FX_POLICY',policy);await approve(db,'TAX_POLICY',taxPolicy);await call(db,'create_cash_register',ids.entityA,ids.cashA,'Confirmed functional bank');return db;}
test('foreign receivables remeasure, partially settle and classify realized and unrealized gains exactly',async()=>{const db=await database();try{
 const created=await approve(db,'FX_DOCUMENT',document());assert.equal(created.foreignAmount,'100.00');assert.equal(created.functionalAmount,'110.00');await remeasure(db,created.documentId,'2026-01-10','1.20');assert.equal(await balance(db,policy.unrealized_gain,'2026-01-10'),'-10.00');
 const paid=await settle(db,created.documentId,'2026-01-11','40.00','1.25','50.00');assert.equal(paid.balance.foreignRemaining,'60.00');assert.equal(paid.balance.carrying,'72.00');assert.equal(paid.balance.historicalRemaining,'66.00');assert.equal(await balance(db,policy.realized_gain,'2026-01-11'),'-6.00');assert.equal(await balance(db,policy.unrealized_gain,'2026-01-11'),'-6.00');
 await remeasure(db,created.documentId,'2026-01-20','1.00');assert.equal(await balance(db,policy.unrealized_gain,'2026-01-20'),'0.00');assert.equal(await balance(db,policy.unrealized_loss,'2026-01-20'),'6.00');await settle(db,created.documentId,'2026-01-21','60.00','1.05','63.00');let r=await report(db,'2026-01-21');assert.equal(r.receivables,'0.00');assert.equal(r.documents[0].state.historicalRemaining,'0.00');assert.equal(r.pendingRemeasurement,0);assert.equal(r.reconciled,true);assert.equal(await balance(db,policy.realized_loss,'2026-01-21'),'3.00');assert.equal(await balance(db,policy.unrealized_loss,'2026-01-21'),'0.00');assert.equal((await report(db,'2026-01-10')).receivables,'120.00');
}finally{await db.close();}});
test('foreign payables apply the opposite gain direction and corrections restore prior carrying and tax sources',async()=>{const db=await database();try{
 const d=await approve(db,'FX_DOCUMENT',document({kind:'PAYABLE',party_id:ids.vendorA,offset_account:ids.expenseA}));await remeasure(db,d.documentId,'2026-01-10','1.20');assert.equal(await balance(db,policy.unrealized_loss,'2026-01-10'),'10.00');const paid=await settle(db,d.documentId,'2026-01-11','50.00','1.00','50.00');assert.equal(paid.balance.carrying,'60.00');assert.equal(await balance(db,policy.realized_gain,'2026-01-11'),'-5.00');
 const corrected=await approve(db,'FX_REVERSE',event(d.documentId,'2026-01-12',{event_id:paid.eventId}));assert.equal(corrected.balance.carrying,'120.00');assert.equal(corrected.balance.foreignRemaining,'100.00');assert.equal(await balance(db,policy.realized_gain,'2026-01-12'),'0.00');const voided=await approve(db,'FX_VOID',event(d.documentId,'2026-01-13'));assert.equal(voided.balance.voided,true);assert.equal((await report(db,'2026-01-13')).payables,'0.00');await approve(db,'FX_REVERSE',event(d.documentId,'2026-01-14',{event_id:voided.eventId}));assert.equal((await report(db,'2026-01-14')).payables,'120.00');assert.equal((await report(db,'2026-01-14')).reconciled,true);
}finally{await db.close();}});
test('foreign tax amounts retain the original conversion and reconcile through a void and correction',async()=>{const db=await database();try{
 const tax={source:'REVIEWED',reference:'SYNTHETIC-FOREIGN-TAX',assessed_on:'2026-01-01',evidence:'Reviewed source-currency assessment and functional tax reporting basis',lines:[{line_number:1,jurisdiction:'US-TEST',treatment:'SALES',basis:'100.00',amount:'10.00'}]};const d=await approve(db,'FX_DOCUMENT',document({tax}));assert.equal(d.foreignAmount,'110.00');assert.equal(d.functionalAmount,'121.00');let register=await call(db,'get_tax_register',ids.entityA,'2026-01-01','2026-01-31');assert.equal(register.controls.find(c=>c.accountId===taxPolicy.sales_account).expected,'11.00');assert.equal(register.foreignDocuments.length,1);assert.equal(register.reconciled,true);
 await remeasure(db,d.documentId,'2026-01-10','1.20');const voided=await approve(db,'FX_VOID',event(d.documentId,'2026-01-11'));register=await call(db,'get_tax_register',ids.entityA,'2026-01-01','2026-01-31');assert.equal(register.controls.find(c=>c.accountId===taxPolicy.sales_account).expected,'0.00');assert.equal(register.reconciled,true);await approve(db,'FX_REVERSE',event(d.documentId,'2026-01-12',{event_id:voided.eventId}));register=await call(db,'get_tax_register',ids.entityA,'2026-01-01','2026-01-31');assert.equal(register.controls.find(c=>c.accountId===taxPolicy.sales_account).expected,'11.00');assert.equal(register.reconciled,true);
}finally{await db.close();}});
test('small partial settlements absorb residual cents without leaving a historical or carrying balance',async()=>{const db=await database();try{
 const d=await approve(db,'FX_DOCUMENT',document({net_amount:'0.03',rate:'1.66666667'}));assert.equal(d.functionalAmount,'0.05');await remeasure(db,d.documentId,'2026-01-02','2.00');for(let n=3;n<=5;n++)await settle(db,d.documentId,'2026-01-0'+n,'0.01','2.00','0.02');const r=await report(db,'2026-01-05');assert.equal(r.receivables,'0.00');assert.equal(r.documents[0].state.historicalRemaining,'0.00');assert.equal(r.reconciled,true);
}finally{await db.close();}});
test('close requires a reviewed cutoff valuation and zero-value rate confirmations remain approved evidence',async()=>{const db=await database();try{
 const d=await approve(db,'FX_DOCUMENT',document());let r=await report(db);assert.equal(r.pendingRemeasurement,1);assert.equal((await call(db,'get_finance_close_check',ids.entityA,'2026-01-01','2026-01-31')).pendingFxRemeasurement,1);const mark=await remeasure(db,d.documentId,'2026-01-31','1.10');assert.equal(mark.journalId,null);assert.equal((await report(db)).pendingRemeasurement,0);
 await actor(db,reviewer);assert.equal((await call(db,'decide_finance_action',mark.req,'APPROVE','Independent currency review')).eventId,mark.eventId);await actor(db,ids.adminA);
 await assert.rejects(call(db,'reverse_posted_journal',d.journalId,'2026-02-01','Detached correction','detached-fx'),/linked document correction/);
}finally{await db.close();}});
test('foreign currency approvals reject wrong cash, overpayments, stale sources, and tenant access',async()=>{const db=await database();try{
 const d=await approve(db,'FX_DOCUMENT',document());await assert.rejects(settle(db,d.documentId,'2026-01-02','100.01','1.10','110.01'),/exact foreign amount/);await assert.rejects(settle(db,d.documentId,'2026-01-02','10.00','1.10','10.99'),/exact foreign amount/);
 const payload=event(d.documentId,'2026-01-10',{rate:'1.20',rate_source:'Synthetic closing quote'});const req=await call(db,'request_finance_action',ids.entityA,'FX_REMEASURE',payload,'Synthetic evidence','pending-fx');await assert.rejects(call(db,'decide_finance_action',req,'APPROVE','Self approval'),/independent/);await settle(db,d.documentId,'2026-01-09','10.00','1.10','11.00');await actor(db,reviewer);await assert.rejects(call(db,'decide_finance_action',req,'APPROVE','Stale source'),/changed/);await actor(db,ids.adminB);await assert.rejects(report(db),/scope/);await actor(db,ids.adminA);await assert.rejects(db.exec('SELECT * FROM public.finance_fx_events'),/permission denied/);
}finally{await db.close();}});
test('retained currency graph corruption prevents financial reports and close acceptance',async()=>{const db=await database();try{
 const d=await approve(db,'FX_DOCUMENT',document());const e=await remeasure(db,d.documentId,'2026-01-31','1.20');await db.exec('RESET ROLE;SET session_replication_role=replica');await db.query("UPDATE public.finance_fx_events SET after_state=jsonb_set(after_state,'{carrying}','\"120.01\"') WHERE id=$1",[e.eventId]);await db.exec('SET session_replication_role=origin;SET ROLE authenticated');await assert.rejects(report(db),/reconcile/);await assert.rejects(call(db,'get_finance_close_check',ids.entityA,'2026-01-01','2026-01-31'),/reconcile/);
}finally{await db.close();}});
test('settlement after fiscal closing recognizes only the new-year exchange movement and preserves the prior close',async()=>{const db=await database();try{
 const retained='30000000-0000-4000-8000-000000000110';await db.exec(`RESET ROLE;INSERT INTO public.accounts VALUES('${retained}','${ids.orgA}','FX3100','FX retained earnings','equity',true);SET ROLE authenticated`);await call(db,'create_accounting_period',ids.entityA,'2025-01-01','2025-12-31','fx-prior-year');
 const d=await approve(db,'FX_DOCUMENT',document({date:'2025-01-01',due_date:'2025-01-31'}));await remeasure(db,d.documentId,'2025-12-31','1.20');const register=(await db.query('SELECT id FROM public.cash_registers WHERE entity_id=$1',[ids.entityA])).rows[0].id;const statement=await call(db,'import_cash_statement',register,{reference:'FX prior year empty bank',starts_on:'2025-01-01',ends_on:'2025-12-31',opening:'0.00',closing:'0.00',lines:[]},'fx-prior-bank');const review=await call(db,'request_cash_review',statement,'CLOSE','Synthetic complete empty bank',(await call(db,'get_cash_reconciliation',statement)).revision);await actor(db,reviewer);await call(db,'decide_cash_review',review,'APPROVE','Independent empty bank completeness');await actor(db,ids.adminA);const c=await approve(db,'FISCAL_YEAR_CLOSE',{starts_on:'2025-01-01',ends_on:'2025-12-31',retained_account_id:retained,attestations:{bank_sources_complete:true,usage_and_contracts_complete:true,unrecorded_liabilities_reviewed:true,asset_policies_reviewed:true,tax_and_opening_balances_reviewed:true}});assert.ok(c.closeId);
 await assert.rejects(remeasure(db,d.documentId,'2025-12-31','1.20'),/open period|closed|finalized|reopen the accepted/);await settle(db,d.documentId,'2026-01-02','100.00','1.25','125.00');assert.equal((await report(db,'2026-01-02')).receivables,'0.00');const profit=(await db.query("SELECT (-sum(l.debit-l.credit))::numeric(38,2)::text AS amount FROM public.journal_lines l JOIN public.journal_entries j ON j.id=l.journal_entry_id JOIN public.accounts a ON a.id=l.account_id WHERE j.entity_id=$1 AND j.entry_date>='2026-01-01' AND a.account_type IN ('revenue','expense')",[ids.entityA])).rows[0].amount;assert.equal(profit,'5.00');
 await db.exec("RESET ROLE;SELECT set_config('request.jwt.claim.sub','',false)");await call(db,'validate_fx_document_graph',d.documentId);await call(db,'validate_fiscal_close_graph',c.closeId);
}finally{await db.close();}});
