import {useState,type FormEvent} from 'react';
import {useQuery} from '@tanstack/react-query';
import {z} from 'zod';
import {AppLayout} from '@/components/layout/AppLayout';
import {FinanceActionForm} from '@/components/finance/FinanceActionForm';
import {FinanceJournalLines} from '@/components/finance/FinanceJournalLines';
import {Evidence,FinanceApprovals} from '@/components/finance/FinanceApprovals';
import {Button} from '@/components/ui/button';
import {useAuth} from '@/hooks/useAuth';
import {useReportEntities} from '@/hooks/useTrialBalance';
import {useAccounts} from '@/hooks/useGeneralLedger';
import {financeResult,requestFinance} from '@/hooks/useFinanceApprovals';
import {supabase} from '@/integrations/supabase/client';
import type {Json} from '@/integrations/supabase/types';
import {readAllRows} from '@/lib/readAllRows';
import {journalLinesFromValues} from '@/lib/financeClose';
import {parseConsolidation,rateRequirementsSchema,groupAttestations,consolidationCsv,statementTotal,downloadFinanceEvidence,type Consolidation,type FxQuote} from '@/lib/groupFinance';

const sourcesSchema=z.object({groupId:z.string().uuid(),hasMore:z.boolean(),rows:z.array(z.object({id:z.string().uuid(),entityId:z.string().uuid(),number:z.string(),date:z.string()}))});
export default function FinanceConsolidation(){const {user,profile}=useAuth();return <AppLayout title="Group consolidation" subtitle="Approved membership, currency translation, eliminations and frozen reports"><Workspace key={`${user?.id}:${profile?.org_id}`}/></AppLayout>;}
function Workspace(){
 const {user,profile}=useAuth(),entities=useReportEntities(),accounts=useAccounts();const [parent,setParent]=useState(''),[selected,setSelected]=useState(''),[from,setFrom]=useState(new Date().getUTCFullYear()+'-01-01'),[through,setThrough]=useState(new Date().toISOString().slice(0,10)),[snapshot,setSnapshot]=useState('');const admin=profile?.role==='admin';
 const history=useQuery({queryKey:['finance-group-history',user?.id,profile?.org_id],enabled:Boolean(user&&profile?.org_id),queryFn:async()=>{const org=profile!.org_id!;const [groups,adjustments,reports]=await Promise.all([
  readAllRows((a,b)=>supabase.from('finance_groups').select('*',{count:'exact'}).eq('org_id',org).order('id').range(a,b)),
  readAllRows((a,b)=>supabase.from('finance_group_adjustments').select('*',{count:'exact'}).eq('org_id',org).order('as_of').order('id').range(a,b)),
  readAllRows((a,b)=>supabase.from('finance_consolidations').select('id,group_id,starts_on,ends_on,active',{count:'exact'}).eq('org_id',org).order('ends_on',{ascending:false}).order('id').range(a,b)),
 ]);return {groups,adjustments,reports};}});
 const group=history.data?.groups.find(g=>g.id===selected),entity=entities.data?.find(e=>e.id===parent),names=new Map([...(accounts.data??[]).map(a=>[a.id,`${a.code} ${a.name}`] as const),...(entities.data??[]).map(e=>[e.id,e.name] as const)]);
 const approved=history.data?.reports.find(r=>r.id===snapshot);
 const saved=useQuery({queryKey:['approved-consolidation',user?.id,profile?.org_id,snapshot],enabled:Boolean(user&&profile?.org_id&&approved),retry:false,queryFn:async()=>{
  const r=z.object({id:z.string().uuid(),active:z.boolean(),approvedAt:z.string(),comparisonAvailable:z.boolean(),sourceChanged:z.boolean().nullable(),report:z.unknown()}).parse(await financeResult(supabase.rpc('get_approved_consolidation',{p_consolidation:snapshot})));
  if(r.id!==snapshot)throw new Error('Approved report scope mismatch.');return {...r,report:parseConsolidation(r.report,{group:approved!.group_id,from:approved!.starts_on,through:approved!.ends_on})};
 }});
 return <div className="space-y-6"><p>Consolidate wholly owned entities in the reporting parent's currency. Source books remain separate. Every final report retains its rates, account reconciliations, membership and approval evidence. Confirm the ownership interval and required acquisition, investment and other adjustments before finalizing.</p>
  {entities.isError||accounts.isError||history.isError?<p role="alert">Group setup or approved history unavailable.</p>:<>
   {admin?<details><summary className="font-semibold">Create an approved reporting group</summary><label>Reporting parent<select aria-label="Reporting parent" className="block w-full rounded border bg-background p-2" value={parent} onChange={e=>setParent(e.target.value)}><option value="">Choose…</option>{entities.data?.map(e=><option value={e.id} key={e.id}>{e.name} ({e.currency})</option>)}</select></label>
    {entity?<FinanceActionForm key={parent} title="Request reporting group" fields={[{name:'reference',label:'Group reference'},{name:'name',label:'Group name'},{name:'date',label:'Approved membership starts',type:'date'},{name:'cta',label:'Group translation equity account',options:accounts.data?.filter(a=>a.is_active&&a.account_type==='equity').map(a=>({value:a.id,label:`${a.code} ${a.name}`}))??[]},{name:'reason',label:'Ownership and consolidation policy evidence'}]} submit={(v,key)=>requestFinance(parent,'GROUP_CREATE',{reference:v.reference,name:v.name,currency:entity.currency,starts_on:v.date,member_ids:[parent,...Object.keys(v).filter(k=>k.startsWith('member-')).map(k=>k.slice(7))],cta_account_id:v.cta,ownership_basis:'WHOLLY_OWNED'},v.reason,key)}>
     <p className="font-semibold">Members · {entity.name} is included as reporting parent</p><div className="grid gap-2 sm:grid-cols-2">{entities.data?.filter(e=>e.id!==parent).map(e=><label key={e.id} className="flex gap-2"><input type="checkbox" name={'member-'+e.id}/>{e.name} ({e.currency})</label>)}</div><label className="flex gap-2"><input required type="checkbox" name="ownership-confirmed"/>These subsidiaries are wholly owned throughout the proposed reporting interval.</label>
    </FinanceActionForm>:null}<p className="text-sm">A definition supports up to 25 members. Create a new approved definition when membership changes. Noncontrolling interests, hyperinflation and transaction-currency remeasurement require separately accepted policies.</p>
   </details>:null}
   <div className="grid gap-3 sm:grid-cols-3"><label>Reporting group<select aria-label="Reporting group" className="block w-full rounded border bg-background p-2" value={selected} onChange={e=>{setSelected(e.target.value);setSnapshot('');}}><option value="">Choose…</option>{history.data?.groups.map(g=><option key={g.id} value={g.id}>{g.name} ({g.currency})</option>)}</select></label><label>Group report starts<input aria-label="Group report starts" className="block w-full rounded border bg-background p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Group report ends<input aria-label="Group report ends" className="block w-full rounded border bg-background p-2" type="date" value={through} onChange={e=>setThrough(e.target.value)}/></label></div>
   {group?<GroupPreparation key={`${group.id}:${from}:${through}`} group={group.id} parent={group.entity_id} from={from} through={through} currency={group.currency} admin={admin} names={names}/>:null}
   {group&&admin?<AdjustmentEditor key={group.id} group={group.id} parent={group.entity_id} currency={group.currency} names={names}/>:null}
   {group?<section className="space-y-3"><h2 className="font-semibold">Group adjustment history</h2>{history.data?.adjustments.filter(a=>a.group_id===group.id).map(a=><article key={a.id} className="rounded border p-3 space-y-2"><h3>{a.reference} · {a.as_of}{a.reversal_date?` · Reversed ${a.reversal_date}`:''}</h3><Evidence value={a.lines} names={names}/>{admin&&!a.reversal_date?<FinanceActionForm title="Request group adjustment reversal" fields={[{name:'date',label:'Group adjustment reversal date',type:'date'},{name:'reason',label:'Group adjustment reversal evidence'}]} submit={(v,key)=>requestFinance(group.entity_id,'GROUP_ADJUSTMENT_REVERSE',{adjustment_id:a.id,date:v.date},v.reason,key)}/>:null}</article>)}</section>:null}
   <section className="space-y-3"><h2 className="font-semibold">Approved consolidation history</h2><label>Approved report<select aria-label="Approved report" className="block w-full rounded border bg-background p-2" value={snapshot} onChange={e=>setSnapshot(e.target.value)}><option value="">Choose…</option>{history.data?.reports.filter(r=>!selected||r.group_id===selected).map(r=><option value={r.id} key={r.id}>{history.data?.groups.find(g=>g.id===r.group_id)?.name} · {r.starts_on} — {r.ends_on} · {r.active?'Final':'Reopened'}</option>)}</select></label>
    {saved.isError?<p role="alert">Approved report unavailable. No previously loaded snapshot is shown.</p>:saved.data?<div className="space-y-3"><p>Approved {saved.data.approvedAt} · {saved.data.active?'Final report':'Reopened report retained for audit'}</p>{!saved.data.comparisonAvailable?<p role="alert">Current source comparison is unavailable. This is the retained approval snapshot.</p>:saved.data.sourceChanged?<p role="alert">Current source records differ from this approved snapshot. Prepare a current comparison before relying on it for a new decision.</p>:<p>The approval snapshot matches current dated source evidence.</p>}<ReportView report={saved.data.report} names={names} label={`Approved snapshot · ${saved.data.active?'Final':'Reopened'} · ${saved.data.approvedAt}`}/>
     {admin&&saved.data.active?<FinanceActionForm title="Request group reopening" fields={[{name:'reason',label:'Group reopening evidence'}]} submit={(v,key)=>{const g=history.data?.groups.find(g=>g.id===saved.data.report.groupId);if(!g)throw new Error('Group unavailable.');return requestFinance(g.entity_id,'GROUP_REOPEN',{consolidation_id:saved.data.id},v.reason,key);}}/>:null}
    </div>:saved.isFetching?<p>Validating the approved snapshot…</p>:null}
   </section>
  </>}
  <FinanceApprovals entityId={group?.entity_id}/>
 </div>;
}
function GroupPreparation({group,parent,from,through,currency,admin,names}:{group:string;parent:string;from:string;through:string;currency:string;admin:boolean;names:Map<string,string>}){
 const {user,profile}=useAuth();const [rates,setRates]=useState<FxQuote[]|null>(null);
 const requirements=useQuery({queryKey:['consolidation-quotes',user?.id,profile?.org_id,group,from,through],retry:false,queryFn:async()=>{const r=rateRequirementsSchema.parse(await financeResult(supabase.rpc('get_consolidation_rate_requirements',{p_group:group,p_from:from,p_through:through})));if(r.groupId!==group||r.from!==from||r.through!==through)throw new Error('Rate requirement scope mismatch.');return r;}});
 const report=useQuery({queryKey:['consolidation-preview',user?.id,profile?.org_id,group,from,through,rates],enabled:rates!==null,retry:false,queryFn:async()=>parseConsolidation(await financeResult(supabase.rpc('get_consolidation_report',{p_group:group,p_from:from,p_through:through,p_rates:rates!})),{group,from,through})});
 function prepare(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!requirements.data)return;const v=Object.fromEntries(new FormData(e.currentTarget));setRates(requirements.data.quotes.map((q,i)=>({...q,rate:String(v['rate-'+i])})));}
 return <section className="space-y-4"><h2 className="font-semibold">Prepare translated group accounts</h2>{requirements.isError?<p role="alert">Consolidation rate requirements unavailable.</p>:requirements.data?<form aria-label="Prepare consolidation" onSubmit={prepare} onChange={()=>setRates(null)} className="space-y-3 rounded border p-4"><p>Enter reporting-currency units per one functional-currency unit. Closing quotes value balance sheets; monthly average quotes value operating activity; historical quotes value equity transactions. Finance must approve the source and suitability of each rate.</p>{requirements.data.quotes.length===0?<p>All members use {currency}; no exchange rates are required.</p>:<div className="grid gap-3 sm:grid-cols-2">{requirements.data.quotes.map((q,i)=><label key={`${q.currency}:${q.kind}:${q.date}`}>{q.currency} · {q.kind.toLowerCase()} · {q.date}<input required aria-label={`${q.currency} ${q.kind} ${q.date} rate`} name={'rate-'+i} className="block w-full rounded border bg-background p-2" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,8})?" placeholder={`1 ${q.currency} = … ${currency}`}/></label>)}</div>}<Button type="submit">Prepare consolidation</Button></form>:<p>Checking source currencies and dated rate requirements…</p>}
  {report.isError?<div className="space-y-2"><p role="alert" className="text-destructive">Consolidation unavailable. Previously loaded figures must not be used.</p><Button variant="outline" onClick={()=>void report.refetch()}>Retry consolidation</Button></div>:rates!==null&&report.data?<>
   <h3 className="font-semibold">{report.data.canFinalize?'Group close checks passed.':'Resolve group close checks before final approval.'}</h3><p>Pending group adjustments: {report.data.pendingGroupAdjustments} · Adjustments with corrected source journals: {report.data.unresolvedAdjustmentSources}</p>
   <ReportView report={report.data} names={names}/><Button variant="outline" onClick={()=>void report.refetch()}>Refresh consolidation</Button>
   {admin&&report.data.canFinalize?<FinanceActionForm title="Request final consolidation" fields={[{name:'reason',label:'Final consolidation evidence'}]} submit={(v,key)=>requestFinance(parent,'GROUP_CONSOLIDATE',{group_id:group,starts_on:from,ends_on:through,rates,attestations:Object.fromEntries(groupAttestations.map(([k])=>[k,v[k]==='on']))},v.reason,key)}>{groupAttestations.map(([k,label])=><label key={k} className="flex gap-2"><input required type="checkbox" name={k}/>{label}</label>)}</FinanceActionForm>:null}
  </>:rates!==null&&report.isFetching?<p>Reconciling source books, rates and eliminations…</p>:null}
 </section>;
}
function AdjustmentEditor({group,parent,currency,names}:{group:string;parent:string;currency:string;names:Map<string,string>}){
 const {user,profile}=useAuth(),accounts=useAccounts();const [search,setSearch]=useState('');
 const sources=useQuery({queryKey:['group-adjustment-sources',user?.id,profile?.org_id,group,search],queryFn:()=>financeResult(supabase.rpc('get_group_adjustment_sources',{p_group:group,p_search:search})).then(v=>sourcesSchema.parse(v))});
 return <details><summary className="font-semibold">Prepare an additional group elimination or adjustment</summary><p>Entries are in {currency} and remain in the group adjustment ledger. Reference the member journals and provide the valuation, ownership or reclassification evidence. Registered cash and the computed translation account cannot be replaced here.</p><label>Find source journal<input aria-label="Find source journal" className="block w-full rounded border bg-background p-2" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/></label>
  {sources.isError||accounts.isError?<p role="alert">Group adjustment sources unavailable.</p>:<FinanceActionForm title="Request group adjustment" fields={[{name:'reference',label:'Group adjustment reference'},{name:'date',label:'Group adjustment date',type:'date'},{name:'reason',label:'Group adjustment policy and valuation evidence'}]} submit={(v,key)=>requestFinance(parent,'GROUP_ADJUSTMENT',{group_id:group,date:v.date,reference:v.reference,lines:journalLinesFromValues(v),source_journals:Object.keys(v).filter(k=>k.startsWith('journal-')).map(k=>k.slice(8))},v.reason,key)}>
   <FinanceJournalLines accounts={accounts.data?.filter(a=>a.is_active)??[]}/><p className="font-semibold">Supporting member journals</p>{sources.data?.hasMore?<p>More than 200 sources match. Narrow the journal search.</p>:null}<div className="max-h-64 space-y-2 overflow-y-auto">{sources.data?.rows.map(j=><label key={j.id} className="flex gap-2"><input type="checkbox" name={'journal-'+j.id}/>{names.get(j.entityId)} · {j.number} · {j.date}</label>)}</div>
  </FinanceActionForm>}
 </details>;
}
function ReportView({report:r,names,label='Prepared consolidation'}:{report:Consolidation;names:Map<string,string>;label?:string}){
 return <div className="space-y-4"><h3 className="font-semibold">{label} · {r.groupName}</h3><p>{r.from} — {r.through} · {r.currency} · Net income {r.netIncome}</p><div className="grid gap-2 sm:grid-cols-3"><p>Revenue {statementTotal(r,'revenue','income',-1n)}</p><p>Expenses {statementTotal(r,'expense','income')}</p><p>Assets {statementTotal(r,'asset','closing')}</p><p>Liabilities {statementTotal(r,'liability','closing',-1n)}</p><p>Recorded equity {statementTotal(r,'equity','closing',-1n)}</p><p>Translation adjustment {r.translationAdjustment}</p></div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left">Signed debit less credit · source balances reconcile to consolidated balances</caption><thead><tr>{['Account','Translated sources','Automatic eliminations','Reviewed adjustments','Translation','Consolidated balance','Period activity'].map(x=><th key={x} className="p-2 text-right first:text-left">{x}</th>)}</tr></thead><tbody>{r.rows.map(a=><tr key={a.accountId} className="border-t"><th className="p-2 text-left">{a.code} {a.name}</th>{[a.sourceClosing,a.automaticClosing,a.adjustmentClosing,a.translationClosing,a.closing,a.income].map((v,i)=><td key={i} className="p-2 text-right tabular-nums">{v}</td>)}</tr>)}</tbody></table></div>
  <div className="flex gap-2"><Button variant="outline" onClick={()=>downloadFinanceEvidence(`consolidation-${r.groupId}-${r.through}.csv`,consolidationCsv(r,label),'text/csv;charset=utf-8')}>Export consolidation CSV</Button><Button variant="outline" onClick={()=>downloadFinanceEvidence(`consolidation-${r.groupId}-${r.through}.json`,JSON.stringify({label,report:r},null,2))}>Export consolidation evidence</Button></div>
  <details><summary>Member close and translation evidence</summary>{r.members.map(m=><div key={m.entityId} className="rounded border p-3 space-y-2"><h4>{m.name} ({m.currency}) · {m.periodsClosed?'Periods closed':'Open periods require review'}</h4><Evidence value={m.closeChecks as Json} names={names}/><p>Translation adjustment {m.translationAdjustment}</p></div>)}</details>
  {r.externalIntercompany.length?<details><summary>Intercompany parties outside this reporting group</summary><Evidence value={r.externalIntercompany as Json} names={names}/></details>:null}
 </div>;
}
