import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {AppLayout} from '@/components/layout/AppLayout';
import {Button} from '@/components/ui/button';
import {FinanceActionForm} from '@/components/finance/FinanceActionForm';
import {FinanceApprovals} from '@/components/finance/FinanceApprovals';
import {FinancialStatementView} from '@/components/finance/FinancialStatementView';
import {useAuth} from '@/hooks/useAuth';
import {useReportEntities} from '@/hooks/useTrialBalance';
import {financeResult,requestFinance} from '@/hooks/useFinanceApprovals';
import {supabase} from '@/integrations/supabase/client';
import {readAllRows} from '@/lib/readAllRows';
import {parseFinancialStatements,statementContextSchema,type CashFlow} from '@/lib/financialStatements';
import type {z} from 'zod';
export default function FinancialStatements(){const {user,profile}=useAuth();return <AppLayout title="Financial statements" subtitle="Approved presentation, classified cash flows and ledger controls"><Workspace key={`${user?.id}:${profile?.org_id}`}/></AppLayout>;}
function Workspace(){
 const {user,profile}=useAuth(),entities=useReportEntities();const [entity,setEntity]=useState(''),[group,setGroup]=useState(''),[from,setFrom]=useState(new Date().getUTCFullYear()+'-01-01'),[through,setThrough]=useState(new Date().toISOString().slice(0,10));
 const groups=useQuery({queryKey:['statement-groups',user?.id,profile?.org_id],enabled:Boolean(user&&profile?.org_id),queryFn:()=>readAllRows((a,b)=>supabase.from('finance_groups').select('id,name,entity_id',{count:'exact'}).eq('org_id',profile!.org_id!).order('id').range(a,b))});
 return <div className="space-y-5"><p>Approve the account presentation for each entity and reporting group. Classify cash receipts and payments using source evidence, then prepare statements that reconcile to the ledger. A new policy version restates current presentation while retaining prior approvals and frozen group snapshots.</p>
  {entities.isError||groups.isError?<p role="alert">Statement setup unavailable.</p>:<><div className="grid gap-3 sm:grid-cols-3"><label>Statement entity<select aria-label="Statement entity" value={entity} onChange={e=>{setEntity(e.target.value);setGroup('');}} className="block w-full rounded border bg-background p-2"><option value="">Choose…</option>{entities.data?.map(e=><option key={e.id} value={e.id}>{e.name} ({e.currency})</option>)}</select></label><label>Statement starts<input aria-label="Statement starts" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block w-full rounded border bg-background p-2"/></label><label>Statement ends<input aria-label="Statement ends" type="date" value={through} onChange={e=>setThrough(e.target.value)} className="block w-full rounded border bg-background p-2"/></label></div>
   {entity?<><label>Presentation scope<select aria-label="Presentation scope" value={group} onChange={e=>setGroup(e.target.value)} className="block w-full rounded border bg-background p-2"><option value="">Entity statements</option>{groups.data?.filter(g=>g.entity_id===entity).map(g=><option key={g.id} value={g.id}>{g.name} · group presentation</option>)}</select></label><StatementWorkspace key={`${entity}:${group}:${from}:${through}`} entity={entity} group={group||null} from={from} through={through}/></>:null}</>}
  <FinanceApprovals entityId={entity||undefined}/>
 </div>;
}
function StatementWorkspace({entity,group,from,through}:{entity:string;group:string|null;from:string;through:string}){
 const {user,profile}=useAuth();const context=useQuery({queryKey:['statement-policy',user?.id,profile?.org_id,entity,group],retry:false,queryFn:async()=>{const r=statementContextSchema.parse(await financeResult(supabase.rpc('get_statement_policy_context',{p_entity:entity,p_group:group})));if(r.entityId!==entity||r.groupId!==group)throw new Error('Statement policy scope mismatch.');return r;}});
 const report=useQuery({queryKey:['financial-statements',user?.id,profile?.org_id,entity,from,through,context.data?.policy?.id],enabled:!group&&Boolean(context.data?.policy)&&!context.isError,retry:false,queryFn:()=>financeResult(supabase.rpc('get_entity_financial_statements',{p_entity:entity,p_from:from,p_through:through})).then(v=>parseFinancialStatements(v,{entity,from,through}))});
 if(context.isError)return <div><p role="alert">Statement policy unavailable.</p><Button onClick={()=>void context.refetch()}>Retry statement policy</Button></div>;if(!context.data)return <p>Loading approved statement policy…</p>;
 const ctx=context.data;
 return <div className="space-y-5">{profile?.role==='admin'?<PolicyEditor key={ctx.policy?.id??'new'} context={ctx}/>:null}{!ctx.policy?<p role="alert">An approved statement policy is required for this reporting scope.</p>:group?<p>Group policy version {ctx.policy.version} is approved. Prepare the report and exchange rates in <a className="underline" href="/consolidation">Group Consolidation</a>.</p>:report.isError?<div><p role="alert">Financial statements unavailable. Previously loaded figures and exports are hidden.</p><Button onClick={()=>void report.refetch()}>Retry financial statements</Button></div>:report.data?<>
  <FinancialStatementView {...report.data} label={report.data.entityName}/><Button variant="outline" onClick={()=>void report.refetch()}>Refresh financial statements</Button>
  {profile?.role==='admin'||profile?.role==='moderator'?<CashEditor key={report.data.cashFlow.revision} cash={report.data.cashFlow} categories={ctx.categories}/>:null}
 </>:<p>Reconciling statement and cash sources…</p>}</div>;
}
function PolicyEditor({context:c}:{context:z.infer<typeof statementContextSchema>}){
 return <details open={!c.policy}><summary className="font-semibold">{c.policy?'Review or revise statement presentation':'Set up approved statement presentation'}</summary><FinanceActionForm title="Request statement policy" fields={[{name:'reason',label:'Statement presentation policy evidence'}]} submit={(v,key)=>requestFinance(c.entityId,'STATEMENT_POLICY',{group_id:c.groupId,expected_version:c.policy?.version??0,cash_accounts:c.cashAccounts,mappings:Object.keys(v).filter(k=>k.startsWith('mapping-')&&v[k]).map(k=>({account_id:k.slice(8),section:v[k]}))},v.reason,key)}>
  <p>Choose presentation based on the account's purpose and your accepted current/noncurrent and expense policies. Bank accounts use the registered cash perimeter. Include retired accounts needed for historical reports.</p><div className="grid max-h-96 gap-3 overflow-y-auto sm:grid-cols-2">{c.accounts.map(a=>{const cash=c.cashAccounts.includes(a.id);return <label key={a.id}>{a.code} {a.name}{a.active?'':' (retired)'}<select aria-label={`Statement mapping ${a.code}`} name={'mapping-'+a.id} defaultValue={c.policy?.mappings.find(m=>m.account_id===a.id)?.section??(cash?'CASH':'')} className="block w-full rounded border bg-background p-2"><option value="">Leave unmapped</option>{c.sections.filter(s=>s.account_type===a.type&&(cash?['CASH','RESTRICTED_CASH_CURRENT','RESTRICTED_CASH_NONCURRENT'].includes(s.section):!['CASH','RESTRICTED_CASH_CURRENT','RESTRICTED_CASH_NONCURRENT'].includes(s.section))).map(s=><option key={s.section} value={s.section}>{s.label}</option>)}</select></label>;})}</div>
 </FinanceActionForm></details>;
}
function CashEditor({cash,categories}:{cash:CashFlow;categories:z.infer<typeof statementContextSchema>['categories']}){
 const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[unclassified,setUnclassified]=useState(true);const rows=cash.sources.filter(s=>(!unclassified||s.classificationId===null)&&`${s.number} ${s.date} ${s.code} ${s.name}`.toLowerCase().includes(search.toLowerCase())),page=rows.slice(offset,offset+20);
 return <details className="space-y-3"><summary className="font-semibold">Classify cash source lines</summary><p>Each selected line must be allocated in full. Split mixed payments between categories. Select both sides of internal transfers in one request; all offsets must share an accounting date. Review existing transfer partners together when changing a prior allocation.</p>
  <label>Find cash source<input aria-label="Find cash source" value={search} maxLength={100} onChange={e=>{setSearch(e.target.value);setOffset(0);}} className="block w-full rounded border bg-background p-2"/></label><label className="flex gap-2"><input type="checkbox" checked={unclassified} onChange={e=>{setUnclassified(e.target.checked);setOffset(0);}}/>Show only unclassified cash lines</label><p>{rows.length} matching lines · Showing {Math.min(offset+1,rows.length)}–{Math.min(offset+20,rows.length)}</p>
  {page.length?<FinanceActionForm key={`${offset}:${search}:${unclassified}`} title="Request cash classifications" fields={[{name:'reason',label:'Cash classification evidence'}]} submit={(v,key)=>requestFinance(cash.entityId,'CASH_FLOW_CLASSIFY',{policy_id:cash.policyId,items:page.filter(s=>v['selected-'+s.lineId]==='on').map(s=>({line_id:s.lineId,expected_version:s.version,allocations:Object.keys(v).filter(k=>k.startsWith('category-'+s.lineId+'-')).map(k=>({category:v[k],amount:v['amount-'+k.slice(9)]}))}))},v.reason,key)}>
   {page.map(s=><CashSourceEditor key={s.lineId} source={s} categories={categories}/>)}
  </FinanceActionForm>:<p>No cash lines match.</p>}
  <div className="flex gap-2"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous cash sources</Button><Button variant="outline" disabled={offset+20>=rows.length} onClick={()=>setOffset(offset+20)}>Next cash sources</Button></div>
 </details>;
}
function CashSourceEditor({source:s,categories}:{source:CashFlow['sources'][number];categories:z.infer<typeof statementContextSchema>['categories']}){
 const [selected,setSelected]=useState(false),[splits,setSplits]=useState(Math.max(1,s.allocations.length));
 return <article className="space-y-2 rounded border p-3"><label className="flex gap-2"><input type="checkbox" name={'selected-'+s.lineId} checked={selected} onChange={e=>setSelected(e.target.checked)}/>{s.number} · {s.date} · {s.code} {s.name} · {s.amount}</label><fieldset disabled={!selected} className="space-y-2">{Array.from({length:splits},(_,i)=><div className="grid gap-2 sm:grid-cols-2" key={i}><label>Cash category {i+1}<select required name={`category-${s.lineId}-${i}`} aria-label={`${s.number} ${s.code} cash category ${i+1}`} defaultValue={s.allocations[i]?.category??''} className="block w-full rounded border bg-background p-2"><option value="">Choose…</option>{categories.map(c=><option key={c.category} value={c.category}>{c.label}</option>)}</select></label><label>Allocation amount {i+1}<input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" name={`amount-${s.lineId}-${i}`} aria-label={`${s.number} ${s.code} cash amount ${i+1}`} defaultValue={s.allocations[i]?.amount??(i===0?s.amount.replace('-',''):'')} className="block w-full rounded border bg-background p-2"/></label></div>)}<Button type="button" variant="outline" disabled={splits>=14} onClick={()=>setSplits(splits+1)}>Split cash allocation</Button>{splits>1?<Button type="button" variant="outline" onClick={()=>setSplits(splits-1)}>Remove last cash split</Button>:null}</fieldset></article>;
}
