import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {AppLayout} from '@/components/layout/AppLayout';
import {FinanceActionForm} from '@/components/finance/FinanceActionForm';
import {FinanceApprovals} from '@/components/finance/FinanceApprovals';
import {TaxAssessmentFields} from '@/components/finance/TaxAssessmentFields';
import {readTaxAssessment} from '@/lib/taxAccounting';
import {parseForeignCurrencyReport} from '@/lib/foreignCurrency';
import {useAuth} from '@/hooks/useAuth';
import {useAccounts} from '@/hooks/useGeneralLedger';
import {useReportEntities} from '@/hooks/useTrialBalance';
import {financeResult,requestFinance} from '@/hooks/useFinanceApprovals';
import {supabase} from '@/integrations/supabase/client';
import {readAllRows} from '@/lib/readAllRows';
import {downloadFinanceEvidence} from '@/lib/groupFinance';
import {Button} from '@/components/ui/button';

export default function ForeignCurrency(){const {user,profile}=useAuth();return <AppLayout title="Foreign currency accounting" subtitle="Foreign receivables, payables and confirmed settlements"><Workspace key={`${user?.id}:${profile?.org_id}`}/></AppLayout>;}
function Workspace(){
 const {user,profile}=useAuth(),accounts=useAccounts(),entities=useReportEntities();const [entity,setEntity]=useState(''),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10)),[kind,setKind]=useState('RECEIVABLE');
 const setup=useQuery({queryKey:['fx-source-setup',user?.id,profile?.org_id],enabled:Boolean(user&&profile?.org_id),retry:false,queryFn:async()=>{const org=profile!.org_id!;const [customers,vendors,cash]=await Promise.all([readAllRows((a,b)=>supabase.from('customers').select('id,name',{count:'exact'}).eq('org_id',org).order('id').range(a,b)),readAllRows((a,b)=>supabase.from('vendors').select('id,name',{count:'exact'}).eq('org_id',org).order('id').range(a,b)),readAllRows((a,b)=>supabase.from('cash_registers').select('*',{count:'exact'}).eq('org_id',org).order('id').range(a,b))]);return {customers,vendors,cash};}});
 const report=useQuery({queryKey:['foreign-currency-report',user?.id,profile?.org_id,entity,asOf],enabled:Boolean(user&&profile?.org_id&&entity&&asOf),retry:false,queryFn:async()=>{const r=parseForeignCurrencyReport(await financeResult(supabase.rpc('get_foreign_currency_report',{p_entity:entity,p_as_of:asOf})));if(r.entityId!==entity||r.asOf!==asOf)throw new Error('Foreign currency scope changed.');return r;}});
 const r=report.data,writable=profile?.role==='admin'||profile?.role==='moderator',error=report.isError||setup.isError||accounts.isError||entities.isError,unavailable=error||report.isFetching||setup.isFetching;
 const options=(type:string)=>(accounts.data??[]).filter(a=>a.account_type===type).map(a=>({value:a.id,label:`${a.code} ${a.name}`}));
 const proofFields=[{name:'date',label:'Currency accounting date',type:'date' as const},{name:'reference',label:'Currency event reference'},{name:'reason',label:'Currency event source evidence'}];
 return <div className="space-y-5"><p>Keep foreign amounts and their functional-currency carrying values together. Approve sourced rates, record confirmed partial payments and remeasure open balances at close. Gains and losses remain traceable to each document.</p><div className="grid gap-3 sm:grid-cols-2"><label>Currency entity<select aria-label="Currency entity" value={entity} onChange={e=>setEntity(e.target.value)} className="block w-full rounded border bg-background p-2"><option value="">Choose…</option>{entities.data?.map(e=><option key={e.id} value={e.id}>{e.name} ({e.currency})</option>)}</select></label><label>Currency report as of<input aria-label="Currency report as of" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} className="block w-full rounded border bg-background p-2"/></label></div><Button variant="outline" disabled={!entity||report.isFetching} onClick={()=>{void report.refetch();void setup.refetch();}}>Refresh currency evidence</Button>
  {error?<p role="alert">Foreign currency balances or source setup are unavailable. Refresh before using balances or exporting evidence.</p>:report.isFetching?<p>Reconciling foreign currency sources…</p>:null}
  {r?<div hidden={unavailable} className="space-y-5"><section className="rounded border p-4"><h2 className="font-semibold">Functional currency balances · {r.currency}</h2><p>Foreign receivables {r.receivables} · Foreign payables {r.payables} · Open balances requiring a rate at this cutoff: {r.pendingRemeasurement}</p>{r.controls.map(c=><p key={c.accountId}>{c.code} {c.name} · Source {c.expected} · Ledger {c.ledger} · Variance {c.variance}</p>)}<p>{r.reconciled?'Foreign currency control accounts reconcile.':'Resolve control differences before closing the period.'}</p></section>
   {!r.policy&&profile?.role==='admin'?<FinanceActionForm title="Request foreign currency policy" fields={[{name:'ar',label:'Foreign receivable control',options:options('asset')},{name:'ap',label:'Foreign payable control',options:options('liability')},{name:'ug',label:'Unrealized currency gain',options:options('revenue')},{name:'ul',label:'Unrealized currency loss',options:options('expense')},{name:'rg',label:'Realized currency gain',options:options('revenue')},{name:'rl',label:'Realized currency loss',options:options('expense')},{name:'reason',label:'Foreign currency policy evidence'}]} submit={(v,key)=>requestFinance(entity,'FX_POLICY',{receivable_account:v.ar,payable_account:v.ap,unrealized_gain:v.ug,unrealized_loss:v.ul,realized_gain:v.rg,realized_loss:v.rl},v.reason,key)}/>:null}
   {r.policy&&writable?<details><summary>Prepare a foreign currency document</summary><label>Foreign document type<select aria-label="Foreign document type" value={kind} onChange={e=>setKind(e.target.value)} className="block w-full rounded border bg-background p-2"><option value="RECEIVABLE">Customer receivable</option><option value="PAYABLE">Supplier payable</option></select></label><FinanceActionForm key={entity+kind} title="Request foreign document posting" fields={[{name:'party',label:'Foreign document party',options:(kind==='RECEIVABLE'?setup.data?.customers:setup.data?.vendors)?.map(p=>({value:p.id,label:p.name}))??[]},{name:'number',label:'Foreign document number'},{name:'date',label:'Foreign document date',type:'date'},{name:'due',label:'Foreign document due date',type:'date'},{name:'currency',label:'Document currency',options:['USD','EUR','GBP','CAD','AUD','NZD','SGD','HKD','CHF'].filter(c=>c!==r.currency).map(c=>({value:c,label:c}))},{name:'net',label:'Original foreign net amount'},{name:'rate',label:`Initial rate (${r.currency} per foreign unit)`},{name:'rate_source',label:'Initial rate source and timestamp'},{name:'offset',label:'Foreign document revenue or expense',options:options(kind==='RECEIVABLE'?'revenue':'expense')},{name:'tax_explanation',label:'Reviewed reason for no tax, if applicable',optional:true},{name:'reason',label:'Foreign document agreement and accounting evidence',type:'textarea'}]} submit={(v,key)=>{const tax=readTaxAssessment(v);return requestFinance(entity,'FX_DOCUMENT',{kind,party_id:v.party,number:v.number,date:v.date,due_date:v.due,currency:v.currency,net_amount:v.net,rate:v.rate,rate_source:v.rate_source,offset_account:v.offset,evidence:v.reason,...(tax?{tax}:{tax_explanation:v.tax_explanation})},v.reason,key);}}><TaxAssessmentFields optional kind={kind==='RECEIVABLE'?'AR':'AP'}/><p>Tax assessments use the document currency. Functional tax amounts use the approved initial rate; any conversion rounding remains in the net operating amount.</p></FinanceActionForm></details>:null}
   {r.documents.map(d=><article key={d.id} aria-label={`Foreign document ${d.number}`} className="space-y-3 rounded border p-4"><h2 className="font-semibold">{d.number} · {d.party} · {d.kind}</h2><p>Original {d.foreignTotal} {d.currency} · Open {d.state.foreignRemaining} {d.currency} · Carrying value {d.state.carrying} {r.currency} · Due {d.dueDate} · {d.overdueDays} days overdue</p><p>Last valuation {d.state.valuationDate} · Rate {d.state.rate}{d.state.voided?' · Voided':''}{d.needsRemeasurement?' · Cutoff valuation required':''}</p>
    {writable&&!d.state.voided&&d.state.foreignRemaining!=='0.00'?<div className="grid gap-4 lg:grid-cols-2"><FinanceActionForm title="Request currency remeasurement" fields={[...proofFields,{name:'rate',label:'Closing rate in functional currency per foreign unit'},{name:'rate_source',label:'Closing rate source'}]} submit={(v,key)=>requestFinance(entity,'FX_REMEASURE',{document_id:d.id,date:v.date,reference:v.reference,evidence:v.reason,rate:v.rate,rate_source:v.rate_source},v.reason,key)}/><FinanceActionForm title="Request confirmed foreign settlement" fields={[...proofFields,{name:'foreign',label:'Foreign amount settled'},{name:'cash',label:'Confirmed functional cash amount'},{name:'rate',label:'Executed settlement rate'},{name:'rate_source',label:'Executed rate confirmation'},{name:'bank',label:'Functional settlement bank',options:setup.data?.cash.filter(c=>c.entity_id===entity).map(c=>({value:c.account_id,label:c.name}))??[]}]} submit={(v,key)=>requestFinance(entity,'FX_SETTLE',{document_id:d.id,date:v.date,reference:v.reference,evidence:v.reason,foreign_amount:v.foreign,cash_amount:v.cash,rate:v.rate,rate_source:v.rate_source,cash_account:v.bank},v.reason,key)}/>{d.state.foreignRemaining===d.foreignTotal?<FinanceActionForm title="Request foreign document void" fields={proofFields} submit={(v,key)=>requestFinance(entity,'FX_VOID',{document_id:d.id,date:v.date,reference:v.reference,evidence:v.reason},v.reason,key)}/>:null}</div>:null}
    {writable&&d.latestActiveEvent?<FinanceActionForm title="Request latest currency event correction" fields={proofFields} submit={(v,key)=>requestFinance(entity,'FX_REVERSE',{document_id:d.id,event_id:d.latestActiveEvent!,date:v.date,reference:v.reference,evidence:v.reason},v.reason,key)}/>:null}
    <details><summary>Currency accounting history</summary><p>Original journal {d.journalId} · Approval {d.requestId}</p>{d.events.map(e=><p key={e.id}>{e.date} · {e.kind} · Foreign {e.foreignAmount} · Cash {e.functionalCash} {r.currency} · Open carrying {e.after.carrying} {r.currency} · Journal {e.journalId??'No ledger change'} · Approval {e.requestId}</p>)}</details>
   </article>)}
  </div>:null}
  {r&&!unavailable?<Button variant="outline" onClick={()=>downloadFinanceEvidence(`foreign-currency-${entity}-${asOf}.json`,JSON.stringify(r,null,2))}>Export currency accounting evidence</Button>:null}<FinanceApprovals entityId={entity||undefined}/>
 </div>;
}
