import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {AppLayout} from '@/components/layout/AppLayout';
import {FinanceActionForm} from '@/components/finance/FinanceActionForm';
import {FinanceApprovals} from '@/components/finance/FinanceApprovals';
import {TaxAssessmentFields} from '@/components/finance/TaxAssessmentFields';
import {useAuth} from '@/hooks/useAuth';
import {useAccounts} from '@/hooks/useGeneralLedger';
import {useReportEntities} from '@/hooks/useTrialBalance';
import {financeResult,requestFinance} from '@/hooks/useFinanceApprovals';
import {supabase} from '@/integrations/supabase/client';
import {readAllRows} from '@/lib/readAllRows';
import {parseTaxRegister,readTaxAssessment} from '@/lib/taxAccounting';
import {downloadFinanceEvidence} from '@/lib/groupFinance';
import {Button} from '@/components/ui/button';

export default function TaxAccounting(){const {user,profile}=useAuth();return <AppLayout title="Tax accounting" subtitle="Sourced tax assessments, credits and reconciled control accounts"><Workspace key={`${user?.id}:${profile?.org_id}`}/></AppLayout>;}
function Workspace(){
 const {user,profile}=useAuth(),entities=useReportEntities(),accounts=useAccounts();const [entity,setEntity]=useState(''),[from,setFrom]=useState(new Date().getUTCFullYear()+'-01-01'),[through,setThrough]=useState(new Date().toISOString().slice(0,10));
 const setup=useQuery({queryKey:['tax-setup',user?.id,profile?.org_id],enabled:Boolean(user&&profile?.org_id),queryFn:async()=>{const org=profile!.org_id!;const [customers,vendors,cash]=await Promise.all([readAllRows((from,to)=>supabase.from('customers').select('id,name',{count:'exact'}).eq('org_id',org).order('id').range(from,to)),readAllRows((from,to)=>supabase.from('vendors').select('id,name',{count:'exact'}).eq('org_id',org).order('id').range(from,to)),readAllRows((from,to)=>supabase.from('cash_registers').select('*',{count:'exact'}).eq('org_id',org).order('id').range(from,to))]);return {customers,vendors,cash};}});
 const report=useQuery({queryKey:['tax-register',user?.id,profile?.org_id,entity,from,through],enabled:Boolean(user&&profile?.org_id&&entity&&from&&through),retry:false,queryFn:async()=>{const r=parseTaxRegister(await financeResult(supabase.rpc('get_tax_register',{p_entity:entity,p_from:from,p_through:through})));if(r.entityId!==entity||r.from!==from||r.through!==through)throw new Error('Tax register scope changed.');return r;}});
 const writable=profile?.role==='admin'||profile?.role==='moderator',r=report.data,unavailable=report.isFetching||report.isError||setup.isError||accounts.isError||entities.isError;
 const accountOptions=(type:string)=>(accounts.data??[]).filter(a=>a.account_type===type&&a.is_active).map(a=>({value:a.id,label:`${a.code} ${a.name}`}));
 return <div className="space-y-5"><p>Post net prices and independently assessed tax together. The tax register follows original invoices and bills, credits and confirmed tax payments. It does not determine registrations or file tax returns.</p>
  <div className="grid gap-3 sm:grid-cols-3"><label>Tax entity<select aria-label="Tax entity" value={entity} onChange={e=>setEntity(e.target.value)} className="block w-full rounded border bg-background p-2"><option value="">Choose…</option>{entities.data?.map(e=><option key={e.id} value={e.id}>{e.name} ({e.currency})</option>)}</select></label><label>Tax register from<input aria-label="Tax register from" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block w-full rounded border bg-background p-2"/></label><label>Tax register through<input aria-label="Tax register through" type="date" value={through} onChange={e=>setThrough(e.target.value)} className="block w-full rounded border bg-background p-2"/></label></div>
  <Button variant="outline" disabled={!entity||report.isFetching} onClick={()=>void report.refetch()}>Refresh tax register</Button>
  {report.isError||setup.isError||accounts.isError||entities.isError?<p role="alert">Tax register or source setup unavailable. Refresh before using balances or exports.</p>:report.isFetching?<p>Reconciling assessed tax…</p>:null}
  {r?<div hidden={unavailable} className="space-y-5"><section><h2 className="font-semibold">Tax control accounts · {r.currency}</h2>{r.controls.map(c=><p key={c.accountId}>{c.code} {c.name} · Source balance {c.expected} · Ledger {c.ledger} · Variance {c.variance}</p>)}<p>{r.reconciled?'Tax control accounts reconcile.':'Tax control accounts have unresolved differences. Resolve them before close.'}</p></section>
   {!r.policy&&profile?.role==='admin'?<FinanceActionForm key={entity} title="Request tax accounting policy" fields={[{name:'sales',label:'Sales tax liability',options:accountOptions('liability')},{name:'recoverable',label:'Recoverable tax asset',options:accountOptions('asset')},{name:'expense',label:'Nonrecoverable tax expense',options:accountOptions('expense')},{name:'reason',label:'Tax account policy evidence'}]} submit={(v,key)=>requestFinance(entity,'TAX_POLICY',{sales_account:v.sales,recoverable_account:v.recoverable,expense_account:v.expense},v.reason,key)}/>:null}
   {r.policy&&writable?<><TaxDocumentForm key={entity+'AR'} kind="AR" entity={entity} parties={setup.data?.customers??[]}/><TaxDocumentForm key={entity+'AP'} kind="AP" entity={entity} parties={setup.data?.vendors??[]}/><details><summary>Record a confirmed tax settlement</summary><FinanceActionForm title="Request tax settlement" fields={[{name:'kind',label:'Tax settlement type',options:[{value:'SALES_PAYMENT',label:'Sales tax paid to authority'},{value:'RECOVERABLE_REFUND',label:'Recoverable tax returned by authority'}]},{name:'date',label:'Tax settlement date',type:'date'},{name:'amount',label:'Tax settlement amount'},{name:'cash',label:'Tax settlement bank account',options:(setup.data?.cash??[]).filter(c=>c.entity_id===entity).map(c=>({value:c.account_id,label:c.name}))},{name:'reference',label:'Tax settlement confirmation'},{name:'reason',label:'Tax settlement evidence'}]} submit={(v,key)=>requestFinance(entity,'TAX_SETTLE',{kind:v.kind,date:v.date,amount:v.amount,cash_account:v.cash,reference:v.reference},v.reason,key)}/></details></>:null}
   <section className="space-y-3"><h2 className="font-semibold">Assessed documents</h2>{r.documents.map(d=><details key={d.id} className="rounded border p-3"><summary>{d.kind} · {d.number} · {d.date} · Net {d.subtotal} · Tax {d.tax} · Gross {d.total} {r.currency}</summary><p>Journal {d.journalId}</p>{writable&&d.canCredit?<FinanceActionForm title="Request assessed document credit" fields={[{name:'number',label:'Tax document credit number'},{name:'date',label:'Tax document credit date',type:'date'},{name:'reason',label:'Full credit agreement evidence'}]} submit={(v,key)=>requestFinance(entity,'TAX_DOCUMENT_CREDIT',{document_id:d.id,number:v.number,date:v.date},v.reason,key)}/>:null}{d.kind==='AR'?<a href="/customer-adjustments" className="underline">Prepare partial credits or refunds</a>:null}</details>)}</section>
   <section className="space-y-3"><h2 className="font-semibold">Tax movements</h2>{r.foreignDocuments.map(d=><p key={d.id}>{d.number} · Assessed tax {d.foreignTax} {d.currency} · Original rate {d.rate} · <a className="underline" href="/foreign-currency">Foreign document accounting</a></p>)}{r.movements.map((m,n)=><p key={`${m.sourceId}:${m.kind}:${m.jurisdiction}:${n}`}>{m.date} · {m.kind} · {m.jurisdiction} · {m.amount} {r.currency} · Journal {m.journalId}</p>)}</section>
   {r.settlements.map(s=><article key={s.id}><p>{s.reference} · {s.date} · {s.amount}{s.reversedOn?` · Corrected ${s.reversedOn}`:''}</p>{writable&&!s.reversedOn?<FinanceActionForm title="Request tax settlement correction" fields={[{name:'date',label:'Tax correction date',type:'date'},{name:'reason',label:'Tax correction evidence'}]} submit={(v,key)=>requestFinance(entity,'TAX_SETTLEMENT_REVERSE',{settlement_id:s.id,date:v.date},v.reason,key)}/>:null}</article>)}
  </div>:null}
  {r&&!unavailable?<Button variant="outline" onClick={()=>downloadFinanceEvidence(`tax-register-${entity}-${through}.json`,JSON.stringify(r,null,2))}>Export tax accounting evidence</Button>:null}<FinanceApprovals entityId={entity||undefined}/>
 </div>;
}
function TaxDocumentForm({kind,entity,parties}:{kind:'AR'|'AP';entity:string;parties:{id:string;name:string}[]}){
 const [lines,setLines]=useState([0]);const label=kind==='AR'?'invoice':'bill';
 return <details><summary>Prepare a tax-bearing {label}</summary><FinanceActionForm title={`Request assessed ${label}`} fields={[{name:'party',label:kind==='AR'?'Assessed invoice customer':'Assessed bill vendor',options:parties.map(p=>({value:p.id,label:p.name}))},{name:'number',label:`Assessed ${label} number`},{name:'date',label:`Assessed ${label} date`,type:'date'},{name:'due',label:`Assessed ${label} due date`,type:'date'},{name:'notes',label:`Assessed ${label} notes`,optional:true},{name:'reason',label:`Assessed ${label} approval evidence`}]} submit={(v,key)=>requestFinance(entity,kind==='AR'?'TAX_INVOICE':'TAX_BILL',{party_id:v.party,number:v.number,date:v.date,due_date:v.due,notes:v.notes,lines:Object.keys(v).filter(k=>k.startsWith('description-')).map(k=>{const n=k.slice(12);return {description:v[k],quantity:v['quantity-'+n],unit_price:v['price-'+n]};}),tax:readTaxAssessment(v)!},v.reason,key)}>
  {lines.map((n,index)=><fieldset key={n} className="grid gap-2 rounded border p-3 sm:grid-cols-3"><legend>Document line {index+1}</legend><label>Description<input aria-label={`Assessed ${label} line ${index+1} description`} name={'description-'+n} required className="block w-full rounded border bg-background p-2"/></label><label>Quantity<input aria-label={`Assessed ${label} line ${index+1} quantity`} name={'quantity-'+n} defaultValue="1" required inputMode="decimal" className="block w-full rounded border bg-background p-2"/></label><label>Net unit price<input aria-label={`Assessed ${label} line ${index+1} price`} name={'price-'+n} required inputMode="decimal" className="block w-full rounded border bg-background p-2"/></label>{lines.length>1?<Button type="button" variant="outline" onClick={()=>setLines(lines.filter(l=>l!==n))}>Remove document line {index+1}</Button>:null}</fieldset>)}<Button type="button" variant="outline" disabled={lines.length>=200} onClick={()=>setLines([...lines,Math.max(...lines)+1])}>Add document line</Button><TaxAssessmentFields kind={kind} lineCount={lines.length}/>
 </FinanceActionForm></details>;
}
