// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { publicEnvironment } from '@/config/publicEnvironment';
import { safeBrowserStorage } from '@/lib/browserStorage';
import type { Database } from './types';

if (!publicEnvironment.ok) {
  throw new Error("Public Supabase configuration is missing or invalid.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const SUPABASE_AUTH_STORAGE_KEY = "tapaano-auth-session";

export const supabase = createClient<Database>(
  publicEnvironment.value.supabaseUrl,
  publicEnvironment.value.supabasePublishableKey,
  {
    auth: {
      storage: safeBrowserStorage,
      storageKey: SUPABASE_AUTH_STORAGE_KEY,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
