// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { publicEnvironment } from '@/config/publicEnvironment';
import { safeBrowserStorage } from '@/lib/browserStorage';
import { configureClientDiagnostics } from '@/lib/clientDiagnostics';
import type { Database } from './types';

if (!publicEnvironment.ok) {
  throw new Error("Public Supabase configuration is missing or invalid.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const SUPABASE_AUTH_STORAGE_KEY = "tapaano-auth-session";

export const supabase = createClient<Database>(
  publicEnvironment.value.supabaseUrl,
  publicEnvironment.value.supabasePublishableKey,
  {
    auth: {
      storage: safeBrowserStorage,
      storageKey: SUPABASE_AUTH_STORAGE_KEY,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

configureClientDiagnostics(async ({ code, release }) => {
  const { data, error: sessionError } = await supabase.auth.getSession();
  if (sessionError) throw new Error("Diagnostic authentication unavailable.");
  if (!data.session) return;
  const { error } = await supabase.rpc("record_client_diagnostic", {
    p_event_code: code,
    p_release_sha: release,
  });
  if (error) throw new Error("Diagnostic persistence unavailable.");
});
